### ISSUE TITLE
Leave the tenant owners to handle namespaced CRDs in their own namespaces

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#112]
# Describe the feature
Leave the tenant owner appropriate RBAC privileges to handle namespaced CRDs in the owned namespaces. Currently, we assign the [pre-defined](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) `admin` ClusterRole to the tenant owner, limited to its namespaces only.

However, this role prevents the tenant owner to handle, e.g. create/get/list/patch/delete namespaced custom resources. For example, the owner cannot create `CI/CD` applications and projects, typically defined as custom resources:

```
$ kubectl auth --as=alice --as-group=capsule.clastix.io can-i get applications.argoproj.io -n oil-utils
no
$ kubectl auth --as=alice --as-group=capsule.clastix.io can-i get appprojects.argoproj.io -n oil-utils
no
```

# What would the new user story look like?
Two options come in my mind:

1. We can define a new ClusterRole for all the Tenant owners, eg. `capsule:tenant-admin`, to use instead of the pre-defined `admin`. This ClusteRole will have permissions `*/*` so any custom resource API is permitted for any Tenant. This may be not the best option.

2. We can add another field in the Tenant manifest where to specify, with more safe granularity, the additional permissions per Tenant. For example, in the tenant `oil` manifest:

```
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  additionalAuthzRules:
  - apiGroups:
     - argoproj.io
    resources:
    - applications
    - appprojects
    verbs:
     - create
     - get
     - list
     - watch
     - update
     - patch
     - delete
```

When the tenant above is created, the Capsule controller generates "aggregate" ClusterRoles from the specs above, eg.:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-oil
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      capsule.calstix.io/aggregate-oil: "true"
rules: [] 
```

and

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capsule-tenant:argoproj.io
  labels:
    capsule.calstix.io/aggregate-oil: "true"
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
```

More details on [Aggregated ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).

# Expected behavior
The ability to install custom resources in owned namespaces open more application scenarios for Capsule:

 ```
$ kubectl auth --as=alice --as-group=capsule.clastix.io can-i get applications.argoproj.io -n oil-utils
yes
$ kubectl auth --as=alice --as-group=capsule.clastix.io can-i get appprojects.argoproj.io -n oil-utils
yes

$ kubectl auth --as=joe --as-group=capsule.clastix.io can-i get applications.argoproj.io -n oil-utils
no
$ kubectl auth --as=joe --as-group=capsule.clastix.io can-i get appprojects.argoproj.io -n oil-utils
no
```

Another benefit from option (2) is give the cluster admin more control on Tenants by assigning them capabilities according to their business profile. For example, tenants who have not bought CI/CD option will not be able to use it.
