### ISSUE TITLE
Capsule configuration via a CRDs

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#122]
With Capsule growing and getting more features, probably we should start thinking about providing an effective way for iterating with Capsule options rather than through CLI flags.

Ingress Controller moved toward a CRDs thanks to Ingress Class (especially, the `.spec.parameters` key as a typed local object reference).

Although this would be nice and cool, wondering if we really need a CRDs: Capsule is expected to run in an exclusive way on the Kubernetes cluster, so that would mean having just a single resource of the custom type and sounds odd.

**Comment by bsctl** [comment]
@prometherion not sure to understand the feature request. Could you please articulate with a bit of more details?

**Comment by prometherion** [comment]
Let's take the example of the tenant prefix enforcement: right now, you have to edit the Capsule `args` Pod specification, adding the flag `--force-tenant-prefix`.

Rather than using CLI flags, we could use an additional CRD manageable by Cluster Administrator, something as:
```yaml
kind: CapsuleConfiguration
apiVersion: capsule.clastix.io/v1alpha1
metadata:
  name: configuration
spec:
  enforceTenantPrefix: true
  userGroup: capsule.clastix.io
  protectedNamespaceRegex: ^.*[-.]system$
```

What I like of this approach is the chance to edit the Capsule behavior at runtime, without the need of restarting the Control Plane.
