### ISSUE TITLE
Let the tenant owner to know the allowed Resources Quota

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#152]
# Describe the feature
Let the tenant owner to know the allowed Resources Quota available in the tenant.

It would be useful to have the annotations, similar to the used resources amount:

```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: capsule-oil-1
  namespace:
  annotations:
    quota.capsule.clastix.io/used-pods: "5"       # <-- already there
    quota.capsule.clastix.io/hard-pods: "10"      # <-- proposed new annotation 
```
Actually, the _ResourceQuota_ object is telling the hard limit but this is for the namespace and not for the whole tenant:

```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: capsule-oil-1
spec:
  hard:
    pods: '10'
status:
  hard:
    pods: '10'    # <-- we have the hard quota in the namespace
  used:
    pods: '5'
```
But this value is adjusted by Capsule when the quota is crossed at tenant level, for example, creating resources in other namespace of the same tenant

```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: capsule-oil-1
spec:
  hard:
    pods: '5'
status:
  hard:
    pods: '5'    # <-- we have the hard quota in the namespace adjusted by Capsule
  used:
    pods: '5'
```

Actually there is no way for the tenant user to know the hard quota for the tenant. Another possible option is to put this info in a _Namespace_ annotation instead of the _ResourceQuota_.

This feature will be used in an external web dashboard (not in this code base) we're building:

- **Resource Quota**: capsule-oil-0 

|Resource Type   |Used Namespace |Used Tenant |Max Allowed Tenant |
|----------------|---------------|------------|------------|
|limits.cpu      |1200m          |2400m       |8           |
|limits.memory   |600Mi          |1200Mi      |16Gi        |
|requests.cpu    |600m           |1200m       |8           |
|requests.memory |60Mi           |120Mi       |16Gi        |

- **Resource Quota**: capsule-oil-1 

|Resource Type   |Used Namespace |Used Tenant | Max Allowed Tenant|
|----------------|---------------|------------|-------------|
|pods            |3              |5           |100          |
|deployments     |0              |1           |50           |
|services        |1              |10          |50           |

- **Resource Quota**: capsule-oil-2 

|Resource Type   |Used Namespace |Used Tenant | Max Allowed Tenant|
|----------------|---------------|------------|-------------|
|requests.storage|10Gi           |10Gi        |500Gi        |
