### ISSUE TITLE
Tenant CRD should not have preserveUnknownFields: true

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#187]
The CRD attribute `preserveUnknownFields` is allowing to put non structured data into the Tenant definition.

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  ingressClasses:
    allowed:
      - caas
    allowedRegex: ''
  mealsOfTheDay:
    allowed:
      - pasta
      - pizza
      - spaghetti
  owner:
    kind: User
    name: alice
```

By default, the `.spec.preserveUnknownFields` field is set to `true`: it's not critical but would be nice to be informed of typos during the specification apply.
