### ISSUE TITLE
Allow multiple tenants reserve the same hostname regex

### ISSUE THREAD

**Issue by GlassOfWhiskey** [clastix/capsule#205]
As a federation owning a multi-tenant cluster, it is a common scenario to enable every tenant to publish sites under the federation domain, e.g. `*.federation.net`. At the moment, this is not possible, since only a single tenant can reserve a specific hostname regex. The only possible scenario with this limitation is to assign each tenant a private subdomain, e.g. `*.tenant1.federation.net` to Tenant 1 and `*.tenant2.federation.net` for Tenant 2. Still, this can be quite restrictive in many cases.

A good feature would be to restrict only fully-specified hostnames to a single tenant, while allowing regex-based hostnames to be shared across multiple tenants. This will solve the issue while still avoiding clearly wrong specifications.

**Comment by bsctl** [comment]
@GlassOfWhiskey thanks for reporting this issue. Actually, the cluster admin can provision multiple tenant having the same hostname regex

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  ingressClasses:
    allowed:
    - caas
    allowedRegex: ""
  ingressHostnames:
    allowedRegex: .federation.net$
  namespaceQuota: 100
  nodeSelector:
    pool: caas
  owner:
    kind: Group
    name: oil
  storageClasses:
    allowed:
    - csi-rbd-sc
    allowedRegex: ""
```

and

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: gas
spec:
  ingressClasses:
    allowed:
    - caas
    allowedRegex: ""
  ingressHostnames:
    allowedRegex: .federation.net$
  namespaceQuota: 100
  nodeSelector:
    pool: caas
  owner:
    kind: Group
    name: oil
  storageClasses:
    allowed:
    - csi-rbd-sc
    allowedRegex: ""
```

The check is on the `allowed` field where two tenants cannot use the same allowed hostname:

```yaml
  ingressHostnames:
     allowed:
     - *.federation.net
```
