### ISSUE TITLE
Allow multiple tenants reserve the same allowed ingress domain

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#206]
# Describe the feature
Currently it not possible to create multiple tenants allowing the same ingress domain as introduced by #162. There are cases, where this is a too strict limitation as reported (incorrectly) by #205.  It would be nice to have a command switch in Capsule to disable the check on allowed ingress domains 

# What would the new user story look like?
A new  command switch in Capsule to disable the check on allowed ingress hostnames:

`--allow-multiple-ingress-domains=false` (default value)

# Expected behavior
Having the switch above set to `true` it is possible to have multiple tenants with same allowed ingress domains

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner:
    kind: User
    name: alice
  ingressHostnames:
     allowed:
     - *.federation.net
```

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: gas
spec:
  owner:
    kind: User
    name: alice
  ingressHostnames:
     allowed:
     - *.federation.net
```

Each of the two tenants above can define an ingress having the same domain `*.federation.net`. For example: `webapp.federation.net` in tenant `oil` and `myapp.federation.net` in tenet `gas`.
