### ISSUE TITLE
Allow by default multiple tenants reserve the same allowed ingress domain

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#207]
# Describe the feature
Multiple tenants cannot be allowed to use same ingress domain as reported in #206.

By introducing a new command switch as in #206 the default value `false` leads to the same behaviour. It would be nice to have the switch set to `true` by default since this is the most common scenario. However, we decided to set the default to `true` in a new major release v0.1.0 since doing it in the current v0.0.5 represents a breaking change for current users.

# What would the new user story look like?

A new command switch in Capsule to disable the check on allowed ingress domains:

`--allow-multiple-ingress-domains=true` (default value)

# Expected behavior
Having the switch above set to `true` it is possible to have multiple tenants with same allowed ingress domains

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner:
    kind: User
    name: alice
  ingressHostnames:
     allowed:
     - *.federation.net
```

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: gas
spec:
  owner:
    kind: User
    name: alice
  ingressHostnames:
     allowed:
     - *.federation.net
```

Each of the two tenants above can define an ingress having the same domain `*.federation.net`. For example: `webapp.federation.net` in tenant `oil` and `myapp.federation.net` in tenet `gas`.
