### ISSUE TITLE
Preventing ingress hostname collision does not work between different namespaces of the same tenant 

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#225]
# Bug description
Preventing ingress hostname collision does not work between different namespaces of the same tenant 

# How to reproduce
As cluster admin, start Capsule with switch to prevent ingress hostname collision

```
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --force-tenant-prefix=true
        - --allow-ingress-hostname-collision=false
        command:
        - /manager
```

As cluster admin, create two tenants

```
cat <<EOF | kubectl apply -f -
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner: # required
    name: alice
    kind: User
---
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: gas
spec:
  owner: # required
    name: alice
    kind: User
EOF
```

As tenant owner, create some ns

```
kubectl --as alice --as-group capsule.clastix.io create namespace oil-production
kubectl --as alice --as-group capsule.clastix.io create namespace oil-development
kubectl --as alice --as-group capsule.clastix.io create namespace gas-development
kubectl --as alice --as-group capsule.clastix.io create namespace gas-production
```

As tenant owner, create an ingress

```
cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: oil-production
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF

ingress.networking.k8s.io/example created
```

Create a second ingress in the same namespace

```
cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example2
  namespace: oil-production
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF
Error from server: error when creating "STDIN": admission webhook "ingress-v1beta1.capsule.clastix.io" denied the request: hostname example.com is already used across the cluster: please, reach out to the system administrators
```

The switch works.

Create another ingress in another tenant

```
cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gas-production
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF


Error from server: error when creating "STDIN": admission webhook "ingress-v1beta1.capsule.clastix.io" denied the request: hostname example.com is already used across the cluster: please, reach out to the system administrators
```

The switch still works.

Create another ingress in a namespace of the same tenant

```
cat <<EOF | kubectl --as alice --as-group capsule.clastix.io apply -f -
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: oil-development
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF

ingress.networking.k8s.io/example created
```

The switch is not working, two ingresses with same hostname

```
kubectl get ing -A
NAMESPACE         NAME                    CLASS    HOSTS                   ADDRESS   PORTS   AGE
oil-development   example                 <none>   example.com                       80      15m
oil-production    example                 <none>   example.com                       80      17m

```

# Expected behavior
Preventing ingress hostname collision always works

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: v0.0.5-rc1
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: v1.19.8
