### ISSUE TITLE
NetworkPolicy pruning is deleting also Tenant ones

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#24]
# Bug description

If the Tenant owner is going to deploy manually some _NetworkPolicy_ resources on their namespaces and a reconciliation occurs, these are going to be deleted.

# How to reproduce

Given the following `np.yaml`:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: dont-delete-me-capsule
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

1. `kubectl apply -f np.yaml`
2. reconcile the Tenant, restarting Capsule for example
3. `kubectl get networkpolicies.networking.k8s.io -w` and notice how it's deleted

# Expected behavior

User _NetworkPolicy_ resource should not be deleted.

# Logs

Irrelevant.

# Additional context

- Capsule version: `0.0.1`
- Kubernetes version: Irrelevant
