### ISSUE TITLE
Multiple Group Ownership of Tenants

### ISSUE THREAD

**Issue by frodopwns** [clastix/capsule#240]
# Describe the feature
Multiple groups can own multiple tenants instead of just one.

Groups:
1. TeamA
    - User: Tom
    - User: Mary
2. TeamB
    - User: Alice
    - User: Jeff

Tenants:
1. Oil
    - Owner: TeamA
2. Gas
    - Owner: TeamB

If users Tom or Mary create a namespace, it increments the namespace count for the Oil tenant.
If users Alice or Jeff create a namespace, it affects the Gas Tenant.
Team A cannot use Team B's namespaces and vice versa.

I believe the current functionality only supports one group for ownership.  You can set the group with `--capsule-user-group` or use the default `capsule.clastix.io`.

Is this something you have considered for the project?

**Comment by prometherion** [comment]
Capsule is already supporting Tenant ownership to groups:

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: team-a
spec:
  owner:
    kind: Group
    name: TeamA
```

The prerequisite to getting it working is the belonging of users to both groups, `capsule.clastix.io and `TeamA` as well: this is documented in the [Tenant owners](https://github.com/clastix/capsule#tenant-owners) section but probably this could be improved if not clear enough.

Actually, the `capsule.clastix.io` group name (customizable using the CLI flag `--capsule-user-group` flag) is just used to discriminate regular users from the ones where the multi-tenancy strategy is applied.

We got already customers in production delegating Tenants to a group of users and it's working great: @MaxFedotov can easily share his feedback, also because I recall he spotted a binary-search bug we had/I introduced. 🤭

**Comment by MaxFedotov** [comment]
Hi @frodopwns.

We are using Active Directory with capsule and everything works just great!
We had a group called `kubernetes-abilitytologin`, for which users require access using our internal access management system. This group is used in a `--capsule-user-group` flag and user must be in this group in order to be able to authorize in kubernetes.

Each user can also be in one or many `ownermember-{team}` groups. When user requests a tenant in our internal kubernetes admin system they had to specify an owner group for this tenant, and then this group is passed to the tenant spec like
```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: mytenant
spec:
  owner:
    kind: Group
    name: ownermember-dba
```

There is many-to-many relation between groups, users, and tenants. One user can be in many groups. And one group can own many tenants.
