### ISSUE TITLE
Namespaces within a Tenant cannot be selected in NetworkPolicies

### ISSUE THREAD

**Issue by stg-0** [clastix/capsule#241]
Hi everyone!

I'm trying the brand new v0.0.5 release and found out that, due to the issue #200, there's no way to reference (using namespaceSelector) a particular Namespace within a tenant in a NetworkPolicy.

As stated in the mentioned issue and in the [official documentation](https://kubernetes.io/docs/concepts/services-networking/network-policies/#what-you-can-t-do-with-network-policies-at-least-not-yet), targeting of namespaces by name in NetworkPolicies is not possible and, with the added functionality, there's no way to tag each Namespace separately.

To be able to reference each Namespace in a NetworkPolicy, a possible solution would be to automatically tag each Namespace with a label with its own name.

Something like this:

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    capsule.clastix.io/tenant: mytenant
    name: mytenant-ns
  name: mytenant-ns
```

**Comment by prometherion** [comment]
Looks good to me: @bsctl @MaxFedotov any remark on this?

I also think this can be a really good first issue, any contribution is highly appreciated! ❤️

**Comment by MaxFedotov** [comment]
We are already doing this in order to support Calico `GlobalNetworkPolicies`.
But we are using `namespacesMetadata.additionalLabels` in Tenant spec:
```yaml
  namespacesMetadata:
    additionalLabels:
      capsule.clastix.io/tenant: {tenant_name}
```
