### ISSUE TITLE
Helm Chart: having two jobs with same name generates a warning in ArgoCD

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#264]
# Bug description
Having two jobs in Helm Chart with the same name generates a warning in ArgoCD. Template manifest: `post-install-job.yaml` and `pre-delete-job.yaml`

```yaml
...
apiVersion: batch/v1kind: Job
metadata:  name: "{{ .Release.Name }}" 
```

# Expected behavior
No such warning  when deploying with ArgoCD

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
