### ISSUE TITLE
Require tenants to use imagePullPolicy as Always

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#271]
# Describe the feature
The Cluster admin can require tenant owners to always use `imagePullPolicy: Always` so that their private images can only be used by those who have the credentials to pull them.

This is also required for SIG multi-tenancy [benchmarks](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/benchmarks) as part of L1 profile.

# What would the new user story look like?

1. the cluster admin creates a tenant manifest as:
```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner:
    name: alice
    kind: User
  allowedImagePullPolicy:
  - Always
  - Never
  - IfNotPresent
```
2. Tenant owner creates a new _Namespace_
3. This is going to be attached to the _Tenant_
4. Tenant owner can only creates pods with allowed `ImagePullPolicy`. When not specified, any value is admitted, including `null`, i.e. defaulted to `Always` if `:latest` tag is specified, or `IfNotPresent` otherwise.

# Expected behavior
see above
