### ISSUE TITLE
Crashing when validating external services

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#291]
# Bug description
Crashing of the Capsule controller when validating external services.

Tenant manifest

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  annotations:
    capsule.clastix.io/enable-node-listing: "true"
    capsule.clastix.io/enable-node-update: "true"
    capsule.clastix.io/enable-node-deletion: "true"
  name: oil
spec:
  owner: # required
    name: alice
    kind: User
  nodeSelector:
    pool: cmp
  ingressHostnames:
    allowedRegex: "^.clastix.io$"
  namespaceQuota: 9 
  ingressClasses:
    allowed:
    - cmp
    - haproxy
    allowedRegex: ""
  storageClasses:
    allowed:
    - standard
    allowedRegex: ""
  containerRegistries:
    allowed:
    - docker.io
    - quay.io
    allowedRegex: ""
  externalServiceIPs:
    allowed:
    - 8.8.8.8
```

External service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-evil-service
  namespace: oil-production
spec:
  selector:
    app: my-evil-dns-server
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 9053
  externalIPs:
    - 8.8.4.5
```

# How to reproduce
1. As cluster admin, create a tenant as above
2. As Tenant owner, create a namespace
3. As tenant owner, create an external service as above

# Expected behavior
Capsule denies the creation of the external service 

# Logs

```
2021-06-15T11:15:37.024Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validating-external-service-ips", "UID": "c61ce7ed-f7ac-451f-bd11-88c2a9b126a9", "kind": "/v1, Kind=Service", "resource": {"group":"","version":"v1","resource":"services"}}
2021/06/15 11:15:37 http: panic serving 10.132.0.10:4976: runtime error: invalid memory address or nil pointer dereference
goroutine 2615 [running]:
net/http.(*conn).serve.func1(0xc000291360)
        /usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x1597640, 0x2285150)
        /usr/local/go/src/runtime/panic.go:971 +0x499
net.networkNumberAndMask(0x0, 0x52b46f, 0xc00052fbc9, 0x7, 0xc00052fc40, 0x10, 0x10)
        /usr/local/go/src/net/ip.go:476 +0x5
net.(*IPNet).Contains(0x0, 0xc00052fc40, 0x10, 0x10, 0x10)
        /usr/local/go/src/net/ip.go:500 +0x2f
github.com/clastix/capsule/pkg/webhook/services.(*handler).handleService(0x22d4300, 0x1932670, 0xc000652880, 0x19439d0, 0xc00003b860, 0xc0000edb00, 0xc000d56d50, 0x24, 0x0, 0x0, ...)
        /workspace/pkg/webhook/services/validating.go:85 +0x985
github.com/clastix/capsule/pkg/webhook/services.(*handler).OnCreate.func1(0x1932670, 0xc000652880, 0xc000d56d50, 0x24, 0x0, 0x0, 0xc000981c60, 0x2, 0xc000981c62, 0x7, ...)
        /workspace/pkg/webhook/services/validating.go:98 +0xe8
github.com/clastix/capsule/pkg/webhook.(*handlerRouter).Handle(0xc0000ed980, 0x1932670, 0xc000652880, 0xc000d56d50, 0x24, 0x0, 0x0, 0xc000981c60, 0x2, 0xc000981c62, ...)
        /workspace/pkg/webhook/router.go:49 +0x435
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(0xc00064f470, 0x1932670, 0xc000652880, 0xc000d56d50, 0x24, 0x0, 0x0, 0xc000981c60, 0x2, 0xc000981c62, ...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/webhook/admission/webhook.go:140 +0xd5
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc00064f470, 0x7f4bb663ecf8, 0xc000cca910, 0xc000a24700)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/webhook/admission/http.go:100 +0xfa5
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f4bb663ecf8, 0xc000cca910, 0xc000a24700)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc00064f6e0, 0x7f4bb663ecf8, 0xc000cca910, 0xc000a24700)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:100 +0xdf
net/http.HandlerFunc.ServeHTTP(0xc00064f830, 0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc00064f920, 0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000ed000, 0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000124380, 0x1930070, 0xc0003fa7e0, 0xc000a24700)
        /usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000291360, 0x1932718, 0xc000652640)
        /usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3013 +0x39b
W0615 11:15:48.319142       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

# Additional context

- Capsule version: 

```
2021-06-15T11:10:18.754Z        INFO    setup   Capsule Version v0.1.0-rc1 8d5391b.dev
2021-06-15T11:10:18.754Z        INFO    setup   Build from: https://github.com/clastix/capsule
2021-06-15T11:10:18.754Z        INFO    setup   Build date: 2021-06-15T08:38:45
2021-06-15T11:10:18.754Z        INFO    setup   Go Version: go1.16.5
2021-06-15T11:10:18.754Z        INFO    setup   Go OS/Arch: linux/amd64
```

- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)

**Comment by prometherion** [comment]
It's not related to external services, but rather, to additional metadata to Namespaces.

```yaml
  namespacesMetadata:
    additionalAnnotations:
      capsule.clastix.io/annotation: value
    additionalLabels:
      key: value
```
