### ISSUE TITLE
Show the cordoning state of a tenant

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#307]
# Describe the feature
Tenant cordoning #288 got very good feedbacks from Capsule adopters. However, having more and more tenants, from operational side, it's not so immediate to understand which tenant is in cordoned state and which is not.

For example we can issue
```
$ kubectl get tnt -l capsule.clastix.io/cordon=enabled
NAME   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER NAME   OWNER KIND   NODE SELECTOR    AGE
oil    9                 3                 alice        User         {"pool":"cmp"}   51m
```

It would be nice to have this info attached to the state of the Tenant CR.

# What would the new user story look like?
The cluster admin cordon one or more tenants for maintenance

```shell
$ kubectl label tenant oil capsule.clastix.io/cordon=enabled
tenant oil labeled
```

He inspects the tenants list

```shell
$ kubectl get tenants -o wide
NAME   STATE   NAMESPACE QUOTA   NAMESPACE COUNT   OWNER NAME           OWNER KIND   NODE SELECTOR    AGE
gas    Active   9                 0                 capsule.clastix.io   Group        {"pool":"cmp"}   33m
gold   Active   9                 0                 engineering          Group        {"pool":"cmp"}   33m
oil    Cordoned 9                 3                 alice                User         {"pool":"cmp"}   33m
sample Active   3                 3                 alice                User         {"pool":"cmp"}   33m
```

He inspects the tenant

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
  labels:
    capsule.clastix.io/cordon: enabled
  annotations:
spec:
status:
  state: cordoned
  namespaces:
  - oil-development
  - oil-marketing
  - oil-production
  size: 3
```
# Expected behavior
Cordoning state of the tenant is attached to tenant state.
