### ISSUE TITLE
Tenant NetworkPolicies added by the tenant owner cannot be deleted nor patched 

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#32]
# Bug description
Tenant NetworkPolicies added by the tenant owner cannot be deleted nor patched

`$ cat networkpolicy.yaml`
 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
  name: custom-network-policy-0
  namespace:
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          capsule.clastix.io/tenant: oil
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

# How to reproduce

Steps to reproduce the behaviour:

1. Given additional network policies the tenant owner has in a namespace

```
$ kubectl get networkpolicies
NAME                      POD-SELECTOR   AGE
capsule-oil-0             <none>         17m
custom-network-policy     <none>         18m
custom-network-policy-0   <none>         13m
```

2. the tenant gets deny when deleting or patching 

```
kubectl apply -f networkpolicy.yaml
Error from server (Capsule Network Policies cannot be updated: please, reach out the system administrators): error when applying patch:
{"metadata":{"labels":null}}
to:
Resource: "networking.k8s.io/v1, Resource=networkpolicies", GroupVersionKind: "networking.k8s.io/v1, Kind=NetworkPolicy"
Name: "custom-network-policy", Namespace: "usl1"
for: "networkpolicy.yaml": admission webhook "validating.network-policy.capsule.clastix.io" denied the request: Capsule Network Policies cannot be updated: please, reach out the system administrators
6:41

kubectl delete -f networkpolicy.yaml 
Error from server (Capsule Network Policies cannot be deleted: please, reach out the system administrators): error when deleting "networkpolicy.yaml": admission webhook "validating.network-policy.capsule.clastix.io" denied the request: Capsule Network Policies cannot be deleted: please, reach out the system administrators
```
# Expected behavior

The tenant owner can create, patch and delete additional network policies in his namespaces

# Logs

```
2020-08-04T16:43:17.003Z        DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validating-v1-network-policy", "UID": "e3ab89ac-3311-45b8-9c59-056a253bdcef", "kind": "networking.k8s.io/v1, Kind=NetworkPolicy", "resource": {"group":"networking.k8s.io","version":"v1","resource":"networkpolicies"}}
2020-08-04T16:43:17.003Z        DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validating-v1-network-policy", "UID": "e3ab89ac-3311-45b8-9c59-056a253bdcef", "allowed": false, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:Capsule Network Policies cannot be deleted: please, reach out the system administrators,Details:nil,Code:403,}"}
```

# Additional context
