### ISSUE TITLE
Auto provision namespaces on tenant creation 

### ISSUE THREAD

**Issue by nmarcetic** [clastix/capsule#325]
# Describe the feature
It would be handy if the tenant namespace can be auto-provisioned on tenant creation. When Bob, as a cluster-admin provisions new tenant oil with three namespaces development, production and test, they are auto-provisioned (e.g namespace admin Alis don't need to create them). It's a bit different from k8s native expi, but very handy in cases when "container as a service" expi is not a case. 
 
# What would the new user story look like?
Cluster admin creates a new tenant with `namespaceAutoProvision` flag 
```
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner:
    name: alice
    kind: User
  namespaceQuota: 3
  namespaceAutoProvision: true
status:
  namespaces:
    oil-development
    oil-production
    oil-test
```

# Expected behavior
When tenant admin Alise lists namespaces she gets 
```
  oil-development
  oil-production
  oil-test
```
And she is set as a namespace admin. 

I am not sure if this is already possible? I didn't saw such [use case](https://github.com/clastix/capsule/tree/master/docs/operator/use-cases) , but if such option exists , please reference it. Thanks
