### ISSUE TITLE
Using capsule on an existing cluster with multiple namespaces

### ISSUE THREAD

**Issue by Nayels** [clastix/capsule#329]
# Describe the feature

What is the correct way for implementing capsule to an existing cluster with multiple namespaces? Are there any caveats? 

If so I would like to take a try at creating a specific use case for administrators that want to implement capsule on an existing cluster.

**Comment by prometherion** [comment]
Thanks for the question, @Nayels.

Capsule can easily be installed on any Kubernetes cluster since it's essentially an add-on and there shouldn't be any incompatibility with other architectures.

Maybe are you referring to how to attach several and already created Namespace resources to a Tenant?

**Comment by Nayels** [comment]
Thanks for the quick reply, @prometherion 

Good to know!  Yes, also.

**Comment by prometherion** [comment]
I think it's feasible, although you could end-up with some duplicated resources, especially for the RoleBinding ones.

What I would suggest is the following:

1. stop Capsule in order to block reconciliations
2. create a Tenant (e.g.: `oil`) with all your requirements and retrieve its UID (`kubectl get tenants.capsule.clastix.io oil --no-headers -o custom-columns=":.metadata.uid"`)
3. edit all the Namespace resources that should be managed by the Tenant, adding the required label (`capsule.clastix.io/tenant=oil`) as well the owner reference, as follows.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  ownerReferences:
  - apiVersion: capsule.clastix.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: oil  # the Tenant name
    uid: 57245074-c8db-4d2e-8982-9cd9f79244f1  # the Tenant UID extracted with action nr. 2
```
4. restart Capsule

I think you could also reuse the [Velero restore script](https://github.com/clastix/capsule/blob/6008373960252fa9c7f161007bf3a0af3294c860/hack/velero-restore.sh) since you just need to label the Namespace resources and the script will attach the Owner Reference, instead of doing that manually.
