### ISSUE TITLE
The tenant nodeSelector is not updated correctly

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#33]
# Bug description
When updating the tenant nodeSelector in the tenant manifest, the new selector is just appended in the tenant namespaces instead of substituted.

# How to reproduce

Steps to reproduce the behaviour:

1. Having a tenant manifest with a given node selector

```yaml
  nodeSelector:
    kubernetes.io/os: linux
```
2. as tenant owner, create a namespace

```bash
$ kubectl create ns usl1
```
3. and check the namespace is correctly labeled

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: usl1
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: kubernetes.io/os=linux
```

4. as cluster admin, update the tenant above as following:
```
  nodeSelector:
    kubernetes.io/hostname: cmp
```
5. back as tenant owner and check the namespace

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: usl1
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: kubernetes.io/hostname=cmp,kubernetes.io/os=linux
```

# Expected behavior

As cluster admin, it should be possible to update correctly the tenant node selector

# Logs

# Additional context

- Capsule version: build for #30 
- Kubernetes version: irrelevant
