### ISSUE TITLE
Block usage of ExternalName Service type

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#339]
A new [CVE has been reported](https://github.com/kubernetes/kubernetes/issues/103675) regarding a possible attack of cross-Namespace network forwarding.

Ingress Controllers are actually trying to mitigate the issue by ignoring the _Service_ resources of `ExternalName` type, would be great blocking creation of these kinds of resources at Tenant level with a new key in the CRD, such as:

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
spec:
  allowedServiceTypes:
    nodePort: <bool>
    externalName: <bool>
```

@MaxFedotov since you worked on the NodePort stuff, WDYT about the updated structure?
