### ISSUE TITLE
Missing migration of enable-node-ports annotation from v1alpha1 to v1beta1

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#342]
# Bug description

Missing migration of enable-node-ports annotation from v1alpha1 to v1beta1

# How to reproduce

```yaml
kubectl create -f - << EOF
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
  annotations:
    capsule.clastix.io/enable-node-ports: "false"
spec:
  owner: # required
    name: alice
    kind: User
EOF
```

after migration becomes

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - kind: User
    name: alice
  enableNodePorts: true
```
# Expected behavior

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - kind: User
    name: alice
  enableNodePorts: false

```

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: `v0.1.0-rc3 98e1640.dev`
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
