### ISSUE TITLE
Group Service options

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#354]
On `v1beta1` we're grouping all the Service options in a new structure key but we're missing the `externalServiceIPs` one.

Having something as follows would be great.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: gas
spec:
  owners:
    -
      kind: User
      name: bob
  serviceOptions:
    additionalMetadata:
      additionalAnnotations:
        capsule.clastix.io/bgp: "true"
      additionalLabels:
        capsule.clastix.io/pool: gas
    allowedServices:
      nodePort: false
      externalName: false
    externalIPs:
      allowed:
        - 10.20.0.0/16
        - "10.96.42.42"
```
