### ISSUE TITLE
Flickering of hard quotas when dealing with multiple resources

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#361]
# Bug description

Creating a Tenant and subsequently a Namespace with the following definition a reconciliation loop for the ResourceQuota is put in place.

# How to reproduce

1. Create the following Tenant

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - kind: User
    name: alice
  resourceQuotas:
    items:
    - hard:
        limits.cpu: "8"
        limits.memory: 16Gi
        requests.cpu: "8"
        requests.memory: 16Gi
    - hard:
        pods: "10"
        services: "50"
    - hard:
        requests.storage: 10Gi
```

2. `kubectl --as alice --as-group capsule.clastix.io create namespace oil-development`
3. `kubectl --namespace oil-development create deployment ...`
4. checks the ResourceQuota hard limits starting flickering

The root cause of this issue is the following section:

```yaml
    - hard:
        pods: "10"
        services: "50"
```

The actual code is expecting a single resource, replacing the entire struct and causing a loop due to reconciliation of changed specifications.

You can notice a switch from `10` to the blocked value, back and forth.

# Expected behavior

Nevertheless managing multiple resources hard limits, the flickering should not occur and a single reconciliation must occour.

# Logs

N.R.

# Additional context

- Capsule version: `7114523`
- Helm Chart version: N.R.
- Kubernetes version: N.R.
