### ISSUE TITLE
support namespace labeling for tenant owners

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#407]
Current capsule and capsule-proxy implementations deny namespace labeling for tenant owners. The background for this decision was that there are a number of labels, which can lead to different security issues when they are added to a namespace (for example, they can allow to bypass Network Policies).

While this is true, sometimes tenant owners need to have and ability to add some well-known labels defined by their environment. For example, this can be different integrations with 3rd party systems (monitoring, configuration management) where we need to match some business applications with Kubernetes namespaces using some predefined and established set of labels.

So to support these cases and not to compromise overall security I propose adding additional `allowedLabels` list to `namespaceOptions` field in `tenantSpec`, where cluster-administrator can provide a list of labels, that tenant owners can modify via `capsule-proxy`

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  namespaceOptions:
    allowedLabels:
     - myorg.net/foo
     - someother.com/bar
```

This will require an additional webhook for namespaces, where we allow modification of only allowed labels for a namespace.

@bsctl, @prometherion WDYT?

**Comment by oliverbaehler** [comment]
What do you guys think about adding a Regex Option? I bootstrap certain namespaces with a helm wrapper. And I don't want users to mess with my lifecycle hooks or really anything helm related. So I would need the option to deny any label starting with `helm.sh/*`

**Comment by MaxFedotov** [comment]
@prometherion i think we can use existing `AllowedListSpec`. WDYT?

**Comment by prometherion** [comment]
I thought the same, @MaxFedotov!

**Comment by MaxFedotov** [comment]
Great, i can start this after my vacation (be back home at September 12th)

**Comment by awoodsprim** [comment]
Just ran into this when using capsule with argocd.  ArgoCD wants to add an annotation and a label to the namespace it is creating.  We are adding an "ownerReference" to the namesapce as well to allow capsule to "adopt" the namespace after argocd creates it.

Unfortunately, capsule then removes the argo annoations and labels and that causes the two controllers to start to fight over the namespace.

Having this sounds like it would allow us to whitelist the annotations and labels that argocd added and let capsule maintain them.

**Comment by prometherion** [comment]
Thanks for this additional use case, @awoodsprim.

Definitely, we're going to support this feature on `v1beta1` using annotations, then we're going to plan a migration for a new API version.

**Comment by MaxFedotov** [comment]
@awoodsprim i think i can propose a more interesting schema with argocd (i am planning to implement in on our production after my vacation). Starting from v1beta1 capsule allows to add multiple owners for tenants, including service accounts. So it will be possible to add argocd service account as an owner to each tenant by default, thus allowing it to create namespaces as a usual tenant user (and it won't be required to set onwerReference manually). And don't forget to add it to userGroupa in capsuleConfiguration crd)

**Comment by awoodsprim** [comment]
@MaxFedotov - With the two tenant owners, creation of a namespace can be done with annotations on the namespace?  I only ask because at the moment annotations added manually thorough kubectl are stripped by capsule as per this ticket.  Therefore, having argocd as a tenant owner will solve the "adoption" issue, but not the annotation / label one (I think)

**Comment by MaxFedotov** [comment]
@awoodsprim thats depends on how you create a namespace. If you create it using yaml file with ns spec - than you can add annotations/labels to it. If you are using auto-create namespace option - than you had to wait until this proposal will be implemented :)

**Comment by MaxFedotov** [comment]
after discussion with @prometherion decided to add additional `protectedLabels` and `protectedAnnotations` fields, where a list of annotations\labels that can't be modified by tenant owner could be stored. This way we will support a scenario, when there is a small list of well-known labels\annotations, which can't be set or modified by a tenant admin (and all others could be added\modified by tenant-admin).
The new structure will look like:
```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  namespaceOptions:
    allowedLabels:
      allowed:
      - myorg.net/foo
      allowedRegex: ^\w+-lb$
    protectedLabels:
    - protected.net/bar
    allowedAnnotations:
      allowed:
      - myorg.net/foo
      allowedRegex: ^\w+-lb$
    protectedAnnotations:
    - protected.net/bar
```
