### ISSUE TITLE
admission webhook "ingress.capsule.clastix.io" denied the request: Index with name field:hostnamePathPair does not exist

### ISSUE THREAD

**Issue by nodefourtytwo** [clastix/capsule#415]
# Bug description

If I create a new Tenant with `apiVersion: capsule.clastix.io/v1beta1` and I try to create an Ingress, I get:

```
Error: admission webhook "ingress.capsule.clastix.io" denied the request: Index with name field:hostnamePathPair does not exist
helm.go:88: [debug] admission webhook "ingress.capsule.clastix.io" denied the request: Index with name field:hostnamePathPair does not exist
```

The problem does not exist if I create a Tenant with `apiVersion: capsule.clastix.io/v1alpha1`

# How to reproduce

```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: redacted
spec:
  owners:
  - name: redacted_sa
    kind: User
  namespaceOptions:
    additionalMetadata:
      labels:
        project: redacted
    quota: 30
```

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: prod
  name: redacted-name
spec:
  tls:
    - hosts:
      - ui.redacted.org
      secretName: redacted-tls
  rules:
  - host: ui.redacted.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redacted-servce-name
            port:
              number: 80 
```

# Expected behavior

An Ingress should be created

# Additional context

- Capsule version: 0.1.0
- Helm Chart version: capsule-0.1.0
- Kubernetes version: 1.19.8

**Comment by bsctl** [comment]
@nodefourtytwo thanks for reporting this. Trying to reproduce it

1. As cluster admin, create the tenant

```yaml
kubectl create -f - << EOF
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: redacted
spec:
  owners:
  - name: redacted_sa
    kind: User
  namespaceOptions:
    additionalMetadata:
      labels:
        project: redacted
    quota: 30
EOF
```

2. As tenant owner, `redacted_sa`, create a namespace in such tenant

`kubectl --as redacted_sa --as-group capsule.clastix.io create ns redacted-production`


3. As tenant owner, create the ingress in the `redacted-production` namespace

```yaml
kubectl --as redacted_sa --as-group capsule.clastix.io -n redacted-production apply -f - << EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: prod
  name: redacted-name
spec:
  tls:
    - hosts:
      - ui.redacted.org
      secretName: redacted-tls
  rules:
  - host: ui.redacted.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redacted-servce-name
            port:
              number: 80 
EOF
```

> Ingress gets created

`ingress.networking.k8s.io/redacted-name created`

Could you please provide logs of the capsule controller during the ingress creation?

As cluster admin:

`kubectl logs -f deploy/capsule-controller-manager -n capsule-system`

**Comment by nodefourtytwo** [comment]
Here are the logs when I apply the ingress:

```
{"level":"debug","ts":"2021-09-09T07:44:01.871Z","logger":"controller-runtime.webhook.webhooks","msg":"received request","webhook":"/cordoning","UID":"946b6797-853c-4c3a-9b3f-88b28b80834e","kind":"networking.k8s.io/v1, Kind=Ingress","resource":{"group":"networking.k8s.io","version":"v1","resource":"ingresses"}}
{"level":"debug","ts":"2021-09-09T07:44:01.871Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/cordoning","code":200,"reason":"","UID":"946b6797-853c-4c3a-9b3f-88b28b80834e","allowed":true}
{"level":"debug","ts":"2021-09-09T07:44:01.936Z","logger":"controller-runtime.webhook.webhooks","msg":"received request","webhook":"/ingresses","UID":"e5d2cbc7-cee7-4ab7-8d18-ee61d3365a49","kind":"networking.k8s.io/v1, Kind=Ingress","resource":{"group":"networking.k8s.io","version":"v1","resource":"ingresses"}}
{"level":"debug","ts":"2021-09-09T07:44:01.937Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/ingresses","code":403,"reason":"Index with name field:hostnamePathPair does not exist","UID":"e5d2cbc7-cee7-4ab7-8d18-ee61d3365a49","allowed":false}
```

FWIW, we tried completely removing and reinstalling Capsule. Not better.
We also have capsule-proxy installed next to capsule, but we don't use it yet.

**Comment by bsctl** [comment]
Is there any other info you can share about your environment to help us with debug?

- Kubernetes setup e.g. KinD, kubeadm, AKS, EKS, GCP, ..
- How do you provision the ingress: helm, raw yaml manifest, ..
- Are you able to create an ingress with `ingress.networking.k8s.io/v1beta1` API?

```yaml
kubectl --as redacted_sa --as-group capsule.clastix.io -n redacted-production apply -f - << EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: redacted-name-v1beta1
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: prod
spec:
  tls:
    - hosts:
      - ui.redacted.org
      secretName: redacted-tls
  rules:
  - host: ui.redacted.org
    http:
      paths:
      - path: /
        backend:
          serviceName: redacted-servce-name
          servicePort: 80
EOF
```

- Are you able to create other resources, eg. pods, services, pvc in the same tenant as tenant owner `redacted_sa` ?
- How do you authenticate the user `redacted_sa`, TLS client certs, OIDC, ..
