### ISSUE TITLE
The need for CapsuleConfiguration?

### ISSUE THREAD

**Issue by brightzheng100** [clastix/capsule#434]
# Describe the feature

I checked the issue history and found that the `CapsuleConfiguration` was created along the evolving of Capsule.
But do we really need such a CRD to handle configuration?

IMHO, such configuration should be easily handled by a ConfigMap.

Meanwhile, I'm thinking of two layers of configurations: **global** and **Tenant-specific**.
In this case, maybe a default configuration can be used, say `ConfigMap/capsule-configuration-default` as the global configuration, while we can have Tenant specific configuration with some simple naming conversion, like `ConfigMap/capsule-configuration-<Tenant>`.

While reconciliation, the controller will merge both as the final configuration for a specific Tenant's final configuration which may bring in more flexibility, compared to only one set of global configuration options.

What do you think?

**Comment by MaxFedotov** [comment]
Hi @brightzheng100! Thanks you for your interest in capsule. 

There is one great feature from the end user perspective to use crds for storing configuration - keys and values in crds are validated upon it schema, thus reducing the risk of accidental misconfiguration.

And regarding tenant specific configuration - isn't it the same thing, that's already exists in tenant crd?

**Comment by brightzheng100** [comment]
Thanks for the prompt reply -- you guys are really responsive.

Having a CRD/CR really can bring in validation through the reconciliation loop but I feel this is slightly overkilled.

> And regarding tenant specific configuration - isn't it the same thing, that's already exists in tenant crd?

No, I'm still talking about the options within `CapsuleConfiguration`.

Let's give it an example.

Assuming the **global config** is like this -- I'm still using the `CapsuleConfiguration` but as what I mentioned I'd suggest a CM:
```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: capsule-configuration-default
spec:
  forceTenantPrefix: false
  protectedNamespaceRegex: ""
  userGroups:
  - capsule.clastix.io
```

An `oil` Tenant might override this by defining a Tenant specific config, like:
```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: capsule-configuration-oil
spec:
  forceTenantPrefix: true
  protectedNamespaceRegex: "oil-admin"
```

As the result, the `Cluster Admin` can define a more stringent control as per the request from `oil` tenant.
