### ISSUE TITLE
Failing to convert Tenants from v1alpha1 to v1beta1

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#440]
# Bug description
Trying to describe a procedure for tenants migration from from `v1alpha1` to `v1beta1` according to https://github.com/clastix/capsule/issues/438#issuecomment-929169090_, we're getting conversion error for tenant having `LimitRanges` set.

# How to reproduce

1. Install Capsule v0.0.5 using Helm Chart `$ helm install capsule capsule_v0.0.5/charts/capsule`
2. Create a tenant with `LimitRanges` set

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
  annotations:
    capsule.clastix.io/enable-node-ports: "false"
    capsule.clastix.io/enable-node-listing: "true"
spec:
  owner: # required
    name: alice
    kind: User
  limitRanges:
  - limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 10Mi 
```

3. tenant gets created
4. uninstall Capsule `$ helm uninstall capsule`
5. upgrade CRDs `$ kubectl apply -f capsule_v0.1.0/charts/capsule/crd`
6. install Capsule v0.1.0 `$ helm install capsule capsule_v0.1.0/charts/capsule`
7. check logs of Capsule `$ kubectl logs -f deploy/capsule-controller-manager`

# Expected behavior
Conversion of tenant  from `v1alpha1` to `v1beta1`

# Logs

```
{"level":"info","ts":"2021-09-28T20:01:38.312Z","logger":"setup","msg":"Capsule Version v0.1.0 94c6a64.dev"}
{"level":"info","ts":"2021-09-28T20:01:38.312Z","logger":"setup","msg":"Build from: https://github.com/clastix/capsule"}
{"level":"info","ts":"2021-09-28T20:01:38.312Z","logger":"setup","msg":"Build date: 2021-09-03T19:09:38"}
{"level":"info","ts":"2021-09-28T20:01:38.312Z","logger":"setup","msg":"Go Version: go1.16.7"}
{"level":"info","ts":"2021-09-28T20:01:38.312Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2021-09-28T20:01:39.268Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2021-09-28T20:01:39.272Z","logger":"setup","msg":"starting manager"}
I0928 20:01:39.273080       1 leaderelection.go:248] attempting to acquire leader lease capsule-system/42c733ea.clastix.capsule.io...
{"level":"info","ts":"2021-09-28T20:01:39.273Z","logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":"2021-09-28T20:01:39.311Z","logger":"KubeAPIWarningLogger","msg":"networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress"}
E0928 20:01:39.312464       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.Tenant: failed to list *v1beta1.Tenant: v1beta1.TenantList.Items: []v1beta1.Tenant: v1beta1.Tenant.Spec: v1beta1.TenantSpec.LimitRanges: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|tRanges":[{}],"netwo|..., bigger context ...|.io","quay.io"],"allowedRegex":""},"limitRanges":[{}],"networkPolicies":[{}],"nodeSelector":{"pool":|...
{"level":"info","ts":"2021-09-28T20:01:39.312Z","logger":"KubeAPIWarningLogger","msg":"extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress"}
```

# Additional context

- Capsule version: v.0.1.0, v0.1.1-rc0
- Helm Chart version: capsule-0.1.1 
- Kubernetes version: v1.20.5
