### ISSUE TITLE
error: admission webhook "owner.namespace.capsule.clastix.io" denied the request

### ISSUE THREAD

**Issue by tomarent** [clastix/capsule#478]
# Bug description

after upgrading to version v0.1.1-rc0, I receive the following error message:

_You do not have any Tenant assigned: please, reach out to the system administrators, error: admission webhook "owner.namespace.capsule.clastix.io" denied the request: You do not have any Tenant assigned: please, reach out to the system administrators_

FYI: the reason for trying version v0.1.1-rc0 is because I was facing the issue explained in issue #415 

# How to reproduce

The helmRelease I am using:

```yaml
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: capsule
          namespace: capsule-system
        spec:
          interval: 10m
          chart:
            spec:
              chart: capsule
              sourceRef:
                kind: HelmRepository
                name: clastix
                namespace: capsule-system
              interval: 10m
          values:
            manager:
              image:
                tag: "v0.1.1-rc0"
              options:
                capsuleUserGroups: ["capsule.clastix.io", "system:serviceaccounts:flux-system"]
                forceTenantPrefix: true
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 256Mi
            serviceAccount:
              name: "capsule-service-account"                  
            webhooks:
              cordoning:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists
              ingresses:
                namespaceSelector:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists
              networkpolicies:
                namespaceSelector:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists
              pods:
                namespaceSelector:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists
              persistentvolumeclaims:
                namespaceSelector:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists
              services:
                namespaceSelector:
                  matchExpressions:
                    - key: capsule.clastix.io/tenant
                      operator: Exists         
```

My CapsuleConfiguration file looks as following:
```yaml
apiVersion: v1
items:
- apiVersion: capsule.clastix.io/v1alpha1
  kind: CapsuleConfiguration
  metadata:
    annotations:
      meta.helm.sh/release-name: capsule
      meta.helm.sh/release-namespace: capsule-system
    creationTimestamp: "2021-11-29T11:07:17Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: capsule
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: capsule
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: capsule-0.1.3
      helm.toolkit.fluxcd.io/name: capsule
      helm.toolkit.fluxcd.io/namespace: capsule-system
    name: default
    resourceVersion: "1414161"
    uid: 9086035a-271d-4f81-82af-452e18a5e881
  spec:
    forceTenantPrefix: true
    protectedNamespaceRegex: ""
    userGroups:
    - capsule.clastix.io
    - system:serviceaccounts:flux-system
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

# Expected behavior

# Logs

```sh
{"level":"debug","ts":"2021-11-29T11:25:46.985Z","logger":"controller-runtime.webhook.webhooks","msg":"wrote response","webhook":"/namespace-owner-reference","code":403,"reason":"You do not have any Tenant assigned: please, reach out to the system administrators","UID":"6b258a89-c1f4-4264-aaf2-6fdad5d4cd45","allowed":false}
```

# Additional context

- Capsule version: v0.1.1-rc0
- Helm Chart version: 0.1.3
- Kubernetes version: 1.21
