### ISSUE TITLE
Unable to start Capsule Controller Manager using the single YAML file installer

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#483]
# Bug description
Unable to start Capsule Controller Manager using the single YAML file installer.

Missing `namespaceSelector` in `pods.capsule.clastix.io` webhook:

```yaml
....
  service:
      name: capsule-webhook-service
      namespace: capsule-system
      path: /pods
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: pods.capsule.clastix.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10

```

# How to reproduce

Use single YAML file installer

# Expected behavior
Capsule is installed correctly

# Logs

```
Events:
  Type     Reason            Age                From                   Message
  ----     ------            ----               ----                   -------
  Normal   SuccessfulCreate  2m30s              replicaset-controller  Created pod: capsule-controller-manager-7cd56cdbf9-7whdm
  Warning  FailedCreate      31s (x15 over 2m)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "pods.capsule.clastix.io": Post "https://capsule-webhook-service.capsule-system.svc:443/pods?timeout=10s": dial tcp 10.96.9.40:443: connect: connection refused

```
# Additional context

- Capsule version: v0.1.1-rc1
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
