### ISSUE TITLE
Dynamic cluster roles for Tenant owners

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#524]
# Current state

For each Tenant owner in a Tenant specification, Capsule is going to grant `admin` capabilities to the created Namespace resources.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: solar
spec:
  owners:
  - kind: User
    name: alice
  - kind: Group
    name: a-team
status:
  namespaces:
    - solar-development
    - solar-production
```

The resulting RoleBinding will be the following:

```
$: kubectl -n solar-development get rolebindings.rbac.authorization.k8s.io -o wide
NAME                ROLE                                    AGE   USERS   GROUPS   SERVICEACCOUNTS
namespace-deleter   ClusterRole/capsule-namespace-deleter   20s   alice   a-team   
namespace:admin     ClusterRole/admin                       20s   alice   a-team

$: kubectl -n solar-production get rolebindings.rbac.authorization.k8s.io -o wide
NAME                ROLE                                    AGE   USERS   GROUPS   SERVICEACCOUNTS
namespace-deleter   ClusterRole/capsule-namespace-deleter   52s   alice   a-team   
namespace:admin     ClusterRole/admin                       52s   alice   a-team
```

# Desired state

The cluster administrator would like to provide a different role rather than `admin`, and eventually, add different roles to each tenant owner.

A proposed definition could look like the following:

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
spec:
  owners:
  - kind: User
    name: alice
    clusterRoleNames:
    - limited-admin
    - namespace-deleter
  - kind: Group
    name: a-team
    clusterRoleNames:
    - limited-admin
```

In that case, users from group `a-team` would be able to manage the Tenant but not deleting any Tenant Namespace: just an example, the feature could provide further multi-tenancy design.

# Implementation

This feature requires a new CRD version, such as `v1beta2` and must be addressed initially using annotations.

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: solar
  annotations:
    clusterrolenames.capsule.clastix.io/user.alice: "limited-admin,namespace-deleter"
    clusterrolenames.capsule.clastix.io/group.a-team: "limited-admin,namespace-deleter"
spec:
  owners:
  - kind: User
    name: alice
  - kind: Group
    name: a-team
```

The pattern for the annotation would be the following: `clusterrolenames.capsule.clastix.io/${KIND}.${NAME}=${COMMA_SEPARATED_VALUES}`

- `KIND` would refer to the `/spec/owners/kind` key
- `NAME` would refer to the `/spec/owners/name` key
- `COMMA_SEPARATED_VALUES` would become the new cluster roles that should be bounded to that owner definition

A backward compatibility must be ensured, creating by default the `namespace-deleter` and `namespace:admin` RoleBindings, even with empty annotations.

# Proposal contributors

- @prometherion 
- @MaxFedotov
