### ISSUE TITLE
Document how Capsule integrates in a Flux GitOps based environment

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#528]
# Describe the feature
Document how Capsule integrates in a Flux GitOps based environment.

# What would the new user story look like?
The cluster admin can learn how to configure a Flux GitOps based environment with Capsule

# Expected behaviour

A detailed user guide is provided into documentation.

**Comment by oliverbaehler** [comment]
Comment for Assignment

**Comment by bsctl** [comment]
Thanks @oliverbaehler  really appreciate.

**Comment by maxgio92** [comment]
Hey @bsctl I was working exactly on the same use case [here](https://github.com/maxgio92/flux2-capsule-multi-tenancy).
And I then came across the issue @oliverbaehler just discussed in #582.

> In my PoC [here](https://github.com/maxgio92/flux2-capsule-multi-tenancy/blob/main/infrastructure/capsule/capsule-namespace-provisioner-clusterrole.yaml#L11) the `patch` and `list` verb permission the GitOps reconciler would need.

## Tenant self-service reconciliation

TL;DR: The tenant owner needs permission to `patch` (also `list`) cluster-scoped Kubernetes resources/objects too.
The flux kustomize-controller in the end will `kubectl apply` the desired state, and as in the PoC it will do it impersonating the Tenant Owner user.

More details on #582 - I recommend reading it.
 
## Enter Capsule Proxy

I see that this use case is perfect for Capsule Proxy. In this way, the tenant resource control and isolation would happen on a step before during the request process as the request would be proxied instead of being validated.

Then, Capsule Proxy would provide the tenant-scoped view of cluster-scoped resources, to the Tenant Owner. From this point on, the Tenant Owner would be safe to `list` and `patch` Namespaces, as he could it do only on his ones.

Also, no further complexity would be introduced.

## Flux + Capsule + Capsule Proxy

In a nutshell, the Kustomize reconciler in order to reconcile the desired state of the tenant - which would be ideally declared and versioned on Git by the tenant owner itself - would impersonate the Tenant Owner SA user and communicate to the Capsule Proxy to also operate on cluster-scoped resources (e.g. Namespace-as-a-service) - and nothing more!

The tenant can configure it through the `Kustomization` [`spec.kubeConfig`](https://fluxcd.io/docs/components/kustomize/api/#kustomize.toolkit.fluxcd.io/v1beta2.KubeConfig) field.

For example, a `Tenant`:
```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: dev-team
spec:
  additionalRoleBindings:
  - clusterRoleName: cluster-admin
    subjects:
    - name: gitops-reconciler
      kind: ServiceAccount
      namespace: dev-team
  owners:
  - name: system:serviceaccount:dev-team:gitops-reconciler
    kind: ServiceAccount
```
would declare its `Namespace`s, through some `Kustomization` like this:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: namespaces
  namespace: dev-team
spec:
  kubeConfig:
    secretRef:
      name: capsule-proxy
      key: kubeconfig
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-team
  path: ./staging/namespaces
  prune: true
```
where the 

## The missing piece

As of now, on this idea the missing piece is the kubeConfig `Secret` being automatically in-place with the Tenant Owner `ServiceAccount` and up-to-date with its token, as the kubeconfig expects a [`secretRef`](https://pkg.go.dev/github.com/fluxcd/pkg/apis/meta#SecretKeyReference) field.


> from [here](https://github.com/maxgio92/flux2-capsule-multi-tenancy/blob/dev-team-capsule-proxy/staging/namespaces-kustomization.yaml).

## WIP

- [flux2-capsule-multi-tenancy with capsule-proxy](https://github.com/maxgio92/flux2-capsule-multi-tenancy/tree/main-capsule-proxy)
- [flux2-capsule-multi-tenancy](https://github.com/maxgio92/flux2-capsule-multi-tenancy)

/cc @prometherion

**Comment by oliverbaehler** [comment]
Yeah that's what our current setup looks like. We have shell-operator in place which dumps kubeconfigs from serviceaccounts into secrets which access the capsule proxy's internal url. We could add something like that to the capsule proxy.

You will still need to get around, since you implement a huge security exploit when just allowing patch privileges #582

**Comment by oliverbaehler** [comment]
Hi @maxgio92, I have tried the approach to allow Flux within tenants, meaning that cross references within namespaces in the same tenant are such which are marked as public, are allowed. But we don't have the time to maintain such policies over time and we are also moving towards argo, so i guess we won't need them anymore (They weren't used in production yet). Maybe it's something usefu. See the following policies:


**helmrelease.policy.yaml**

```
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-helmrelease-cross-reference
  annotations:
    policies.kyverno.io/title: Flux Helmrelease Cross Reference
    policies.kyverno.io/category: Flux
    policies.kyverno.io/subject: HelmRelease
    policies.kyverno.io/description: >-
      Disallows cross namespaces references of HelmRelease Resources.
spec:
  validationFailureAction: enforce
  background: false
  rules:

    # Defaults all namespace attributes to the namespace the Helmrelease is installed into.
    # Does not overwrite if set
    - name: HelmRelease Default Namespaces
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: In
            value: [ "CREATE", "UPDATE" ]
      match:
        all: 
          - resources:
              kinds:
                - HelmRelease
      exclude:
        any:
          - clusterRoles:
            - cluster-admin
      mutate:
        patchStrategicMerge:
          spec:
            +(targetNamespace): "{{request.object.metadata.namespace}}"
            +(storageNamespace): "{{request.object.metadata.namespace}}"
            +(spec):
              +(sourceRef):
                +(namespace): "{{request.object.metadata.namespace}}"

    # Disallow Source References 
    # Unless in Public Namespace or same Tenant
    - name: helmrelease-source-cross-reference
      context:

        # Load Gloabl Configuration
        - name: global
          configMap:
            name: kyverno-global-config
            namespace: kyverno-system

        # Get All Public Namespaces
        - name: public_namespaces
          apiCall:
            urlPath: "/api/v1/namespaces"
            jmesPath: "items[?metadata.labels.\"{{global.data.public_identifier_label}}\" == '{{global.data.public_identifier_value}}'].metadata.name | []" 

        # Get Tenant information from source namespace
        # Defaults to a character, which can't be a label value
        - name: source_tenant
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}"
            jmesPath: "metadata.labels.\"{{global.data.tenant_identifier_label}}\" | '?'"

        # Get Tenant information from destination namespace
        # Returns Array with Tenant Name or Empty
        - name: destination_tenant
          apiCall:
            urlPath: "/api/v1/namespaces"
            jmesPath: "items[?metadata.name == '{{request.object.spec.chart.spec.sourceRef.namespace}}'].metadata.labels.\"{{global.data.tenant_identifier_label}}\""

      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: In
            value: [ "CREATE", "UPDATE" ]
        any: 

          # Source is not Self-Reference  
          - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
            operator: NotEquals
            value: "{{request.object.metadata.namespace}}"

          # Source not in Public Namespaces
          - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
            operator: NotIn
            value: "{{public_namespaces}}"

          # Source not in Destination
          - key: "{{request.object.spec.chart.spec.sourceRef.namespace}}"
            operator: NotIn
            value: "{{destination_tenant}}"

      match:
        all: 
          - resources:
              kinds:
                - HelmRelease
      exclude:
        any:
          - clusterRoles:
            - cluster-admin
      validate:
        message: "Can not use namespace {{request.object.spec.chart.spec.sourceRef.namespace}} as source reference!"
        deny: {}
```

**kustomization.policy.yaml**

```
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: flux-kustomization-cross-reference
  annotations:
    policies.kyverno.io/title: Flux Kustomization Cross Reference
    policies.kyverno.io/category: Flux
    policies.kyverno.io/subject: Kustomization
    policies.kyverno.io/description: >-
      Disallows cross namespaces references of Kustomization Resources
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: flux-kustomization-defaults
      preconditions:
        any:
          - key: "{{ request.operation }}"
            operator: In
            value: [ "CREATE", "UPDATE" ]
      match:
        all: 
          - resources:
              kinds:
                - Kustomization
      exclude:
        any:
          - clusterRoles:
            - cluster-admin
      mutate:
        patchStrategicMerge:
          spec:
            +(targetNamespace): "{{request.object.metadata.namespace}}"
            +(sourceRef):
              +(namespace): "{{request.object.metadata.namespace}}"

    # Disallow Source References 
    # Unless in Public Namespace or same Tenant
    - name: helmrelease-source-cross-reference
      context:

        # Load Gloabl Configuration
        - name: global
          configMap:
            name: kyverno-global-config
            namespace: kyverno-system

        # Get All Public Namespaces
        - name: public_namespaces
          apiCall:
            urlPath: "/api/v1/namespaces"
            jmesPath: "items[?metadata.labels.\"{{global.data.public_identifier_label}}\" == '{{global.data.public_identifier_value}}'].metadata.name | []" 

        # Get Tenant information from source namespace
        # Defaults to a character, which can't be a label value
        - name: source_tenant
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.object.metadata.namespace}}"
            jmesPath: "metadata.labels.\"{{global.data.tenant_identifier_label}}\" | '?'"

        # Get Tenant information from destination namespace
        # Returns Array with Tenant Name or Empty
        - name: destination_tenant
          apiCall:
            urlPath: "/api/v1/namespaces"
            jmesPath: "items[?metadata.name == '{{request.object.spec.chart.spec.sourceRef.namespace}}'].metadata.labels.\"{{global.data.tenant_identifier_label}}\""

      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: In
            value: [ "CREATE", "UPDATE" ]

          - key: "{{request.object.spec.sourceRef.namespace}}"
            operator: NotIn
            value: "{{public_namespaces}}"

          - key: "{{request.object.spec.targetNamespace}}"
            operator: NotIn
            value: "{{destination_tenant}}"

      match:
        all: 
          - resources:
              kinds:
                - Kustomization
      exclude:
        any:
          - clusterRoles:
            - cluster-admin
      validate:
        message: "Can not use namespace as source reference, namespace must be public or within tenant!"
        deny: {}
```

**global.config.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-global-config
  namespace: kyverno-system
data:
  #
  ## Flux Configurations
  #

  public_identifier_label: "company.com/public"
  public_identifier_value: "true"


  #
  ## Tenant Configurations
  #

  ## tenant_identifier_label
  #    Label which is used to select the tenant name
  tenant_identifier_label: "capsule.clastix.io/tenant"
```
