### ISSUE TITLE
Provide an endpoint for liveness and readiness probes

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#55]
# Describe the feature
As best practice, we should define readiness and liveness probes for any container providing a service and this is also true for capsule controller being a critical service.

Currently the capsule controller exposes only the web-hook port 9443 but this port is not suitable for probing:

```
$ curl -k https://10.38.0.29:9443
404 page not found

$ curl -k https://10.38.0.29:9443/validating-v1-pvc
{"response":{"uid":"","allowed":false,"status":{"metadata":{},"message":"contentType=, expected application/json","code":400}}}
```

# Expected behavior
We need a couple of endpoints for liveness and readiness probing, for example:

```
$ curl -k https://10.38.0.29:10080/health
ok

$ curl -k https://10.38.0.29:10080/ready
ok
```

so we can write readiness and liveness probes:

```yaml
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 10080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /ready
        port: 10080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

Readiness should return ok only when all the stuff are ready, for example when the CA generation succeeded.
