### ISSUE TITLE
Grant Global Namespace Patch Rights

### ISSUE THREAD

**Issue by oliverbaehler** [clastix/capsule#582]
# Describe the feature

For users to be able to bootstrap namespaces via Kustomize oder Helm we need global Patch Rights. Because both actions perform a PATCH operation (Dry-Run) on the namespace API when they try to create a namespace. Currently this is not possible:

```
tenants     sample-tenant   False   Namespace/sample-tenant-app-1 dry-run failed, reason: Forbidden, error: namespaces "sample-tenant-app-1" is forbidden: User "system:serviceaccount:tenants:sample-tenant" cannot patch resource "namespaces" in API group "" in the namespace "sample-tenant-app-1"   17h
```

If we implement this functionality we can provide true namespace self service to our developers/customers.
Currently we have a Kyverno Policy which validates this for us, because we grant global PATCH rights to all capsule users. But we have to validate, that patches are only allowed on namespaces which **don't exist** yet or are part of an owned tenant. The policy looks something like this:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-namespace-edge
spec:
  background: false
  validationFailureAction: "enforce"
  rules:

  - name: disallow-namespace-patch
    context:
    - name: serviceaccount_tenant
      apiCall:
        urlPath: "/api/v1/namespaces/{{serviceAccountNamespace}}/serviceaccounts/{{serviceAccountName}}"
        jmesPath: "not_null(metadata.labels.\"capsule.clastix.io/tenant\")"
    - name: outer_tenant_namespaces
      apiCall:
        urlPath: "/api/v1/namespaces"
        jmesPath: "items[?metadata.labels.\"capsule.clastix.io/tenant\" == \"{{serviceaccount_tenant}}\"].metadata.name"
    match:
      all:
      - resources:
          kinds:
          - Namespace
    exclude:
      any:
      - clusterRoles:
        - cluster-admin
    validate:
      message: "Namespace {{request.object.metadata.name}} has already a date!"
      deny:
        conditions:
          all:

          # Action Must Be Update or Create
          - key: "{{request.operation}}"
            operator: In
            value: ["UPDATE", "CREATE"]

          # If Namespace not in namespaces outer edges (Deny if in) 
          any:  
          - key: "{{request.object.metadata.name}}"
            operator: In
            value: "{{outer_tenant_namespaces}}"
          - key: "{{request.oldObject.metadata.name}}"
            operator: In
            value: "{{outer_tenant_namespaces}}"
```

We are no longer satisfied with the performance of Kyverno, since it caused already multiple outages in our environments. Therefor we would like to implement this feature into capsule directly. This would allow a cleaner Git Flow without any other dependencies. If that is resolved I can bring up a proposal for  #528 

# What would the new user story look like?

How would the new interaction with Capsule look like? E.g.

1. Grant all users PATCH rights via clusterRole `capsule-namespace-provisioner`
2. Add a namespace webhook handler which validates PATCH events on namespaces
  * Non-Existent namespace are granted
  * If Exist: the patch rights are given via `namespace:admin`. But we still have to validate if the namespace is in a tenant owned by 

# Expected behavior

Kustomizations via Kustomize-Controller can apply Namespaces in a safe way.

**Comment by oliverbaehler** [comment]
@maxgio92 **Don't use this in production. If someone pushes a namespace that exists into the repository they can hijack it into a tenant and have full control over it!**

You can reproduce this by adding a namespace manifest called `kube-system` to your repository. You will see that it's added to the tenant and therefor hijacked.

**Comment by maxgio92** [comment]
Of course @oliverbaehler, the workaround I linked is absolutely bad :-)
For that reason I think we need the work @prometherion explained. As a detail, when used Capsule Proxy the kubeconfig provided to the GitOps reconciler will be used, without impersonation I'd say.
Also, the ClusterRole with `patch` privilege on Namespace should be bound only if using Capsule Proxy.

**Comment by prometherion** [comment]
> Also, the ClusterRole with `patch` privilege on Namespace should be bound only if using Capsule Proxy.

What do you mean here?

**Comment by maxgio92** [comment]
> > Also, the ClusterRole with `patch` privilege on Namespace should be bound only if using Capsule Proxy.
> 
> What do you mean here?

I think I made a wrong assumption about the fact we need proxy to filter also results from `patch` requests.
That should be true only for `list`.

**Comment by JimBugwadia** [comment]
> We are no longer satisfied with the performance of Kyverno, since it caused already multiple outages in our environments

Hi @oliverbaehler - I am a Kyverno maintainer and would love to learn more about the problems you faced so we can improve in this area. There were a number of memory and performance related updates in 1.7.2 and we would like to capture more scenarios to test. Can you please create an issue or discussion in the Kyverno repo for this?

**Comment by chipzoller** [comment]
@oliverbaehler second maintainer here and I'm sorry to hear about the issues that you encountered. Did you ever come talk to us in the #kyverno channel in Kubernetes Slack about this? Or was there some other venue/channel you tried and didn't get satisfactory help?

**Comment by oliverbaehler** [comment]
Hi @chipzoller  @JimBugwadia, thanks for the proactive approach. I have removed the comment now since that was pointless blaming from my side (Kubernetes gets overwhelming with absolutely no staff). So what happened: We had Policies deployed which were just so resource intense, that the controllers were constantly under CPU pressure, resulting in often getting webhook timeouts. Also noone monitored the performance of the kyverno controllers. When we had the policies in place the resource usage looked like this:

![image](https://user-images.githubusercontent.com/26610571/181829763-630b8266-f806-4dff-800e-379457005c84.png)

After removing some of the policies:

![image](https://user-images.githubusercontent.com/26610571/181829859-969fc7c0-e8a4-4fdf-b5c1-226727c97f1f.png)

So yeah, difference between night and day! The policies weren't tested enough especially how the load differs from dev clusters to production clusters, where it gets much more intense. And just to show, we are talking about such policies:

```
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-disallow-patch
  annotations:
    policies.kyverno.io/title: Tenant Namespace Protection
    policies.kyverno.io/category: Tenant
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/description: >-
      Disallow the patch of the reserved namespace for tenant users
spec:
  validationFailureAction: enforce
  background: false
  rules:

  # Disallow labeld resources patch
  - name: disallow-resource-patch
    context:
    - name: global
      configMap:
        name: kyverno-global-config
        namespace: kyverno-system
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
          - UPDATE  
      - key: "{{global.data.tenant_disallow_patch_label}}"
        operator: Equals
        value: "true"
    match:
      all:
      - resources:
          kinds:
          - '*'

    # Needs Administrator Privileges      
    exclude:
      clusterRoles:
      - cluster-admin

    # Validation Message
    validate:
      message: "Deleting {{request.object.kind}}/{{request.object.metadata.name}} is not allowed"
      deny: {}
```

Obviously that runs for every PATCH operation, which can get intense.

We are currently running Kyverno in Version `2.5.1` on all our clusters without any issues. And we are planning on using it for the future, just with better policy testing.. :). Sorry for the unnecessary comment, big fan of the work! ❤️
