### ISSUE TITLE
Default Value PriorityClass/storageClasses/allowedClasses

### ISSUE THREAD

**Issue by oliverbaehler** [clastix/capsule#610]
# Describe the feature

Generally it's a default value for `priorityClasses`, `storageClasses` and `allowedClasses` (Ingress). Adding a default value would simplify working in the tenant for the customer, since they wouldn't have to worry to much about these values, since a default value is applied. But then con overwrite it, by setting their value.

Would you be happy to accept this feature(s)? I will do the contribution.

# What would the new user story look like?

Story for PriorityClasses.

Add the feature to define a default PriorityClass for all pods within the tenant. The given default PriorityClass would be assigned to all pods, which don't have a priorityClass set. If a PriorityClass is set on a pad, the default is ignored. The default value is also verified against the allowed/regex.

A new tenant is created. The customer can assign two tiers `tier-gold` and `tier-silver`. To make it more convenient to user only has to tag pods with higher priority with `tier-gold`. While all the other pods are assigned the `tier-silver`. Manifest could look like this:

```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  priorityClasses:
    default: "tier-silver"
    allowed:
    - default
    allowedRegex: "^tier-.*$"
```

**Comment by oliverbaehler** [comment]
Maybe it would even make sense adding a namespace selector.


```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  priorityClasses:
    defaults:
      - value: "tier-prod"
         namespaceSelector:
            matchExpressions:
              - {key: environment, operator: NotIn, values: [dev]}
      - value: "tier-silver"
         namespaceSelector:
            matchExpressions:
              - {key: environment, operator: In, values: [dev]}
    allowed:
    - default
    allowedRegex: "^tier-.*$"
```
