### ISSUE TITLE
Clarify the design of the clusterrole assigment tenant owners

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#615]
# Bug description
In documentation, clarify the usage of `clusterroles` that can be assigned to a tenant owner `alice` by the annotation: `clusterrolenames.capsule.clastix.io/user.alice: editor,manager`.

Currently, assigning a `clusterrole` to a tenant owner in such way, Capsule prevents the tenant owner `alice` to act as namespaces admin by missing the default and usual `rolebindings`: `capsule-oil-1-admin` and `capsule-oil-2-capsule-namespace-deleter`.

This is by design, however the tenant owner `alice` can still create namespaces in the tenant because she always belongs to the `capsule.clastix.io` group, so we end up in a case where the tenant owner `alice` can create namespaces but cannot operate or delete them, unless `clusterroles` are explicit assigned, for example:

`clusterrolenames.capsule.clastix.io/user.alice: editor,manager,capsule-namespace-deleter`

Just clarify this design in the documentation.

# How to reproduce

Create a tenant

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  annotations:
    clusterrolenames.capsule.clastix.io/user.alice: editor,manager
  name: oil
spec:
  owners:
    - kind: User
      name: alice
    - kind: ServiceAccount
      name: system:serviceaccount:default:robot
  namespaceOptions:
    quota: 3

```

# Expected behavior

Clarify this behaviour in documentation.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
