### ISSUE TITLE
Support for new PodSecurityStandard as replacement for PodSecurityPolicy

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#616]
# Describe the feature
[PodSecurityPolicy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) exists in Kubernetes to provide security controls. PSPs are deprecated in Kubernetes 1.21 and will be removed entirely in 1.25. As replacement, Kubernetes introduced the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). The Capsule operator should support the new standard for tenants under its control.

# What would the new user story look like?
The Pod Security Standards define three different policies to broadly cover the security spectrum. These policies are cumulative and range from highly-permissive to highly-restrictive:

Profile | Description
-- | --
Privileged | Unrestricted policy, providing the widest possible level of permissions. This policy allows for known privilege escalations.
Baseline | Minimally restrictive policy which prevents known privilege escalations. Allows the default (minimally specified) Pod configuration.
Restricted | Heavily restricted policy, following current Pod hardening best practices.

Kubernetes provides a built-in [admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podsecurity) to enforce the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards) at either:

1. cluster level which applies a standard configuration to all namespaces in a cluster
2. namespace level, one namespace at a time

For the first case, you should configure the Pod Security Admission Controller and pass the configuration to the `kube-apiserver` by mean of the `--admission-control-config-file` extra argument, for example:

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1beta1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: [kube-system]
```

For the second case, you can just assign labels to the specific namespace you want enforce the policy since the Pod Security Admission Controller is enabled by default starting v1.23+:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: development
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
  name: development
```

## How to bring PodSecurityStandard in Capsule (proposal)
According to Kubernetes segregation model, you have to operate either at cluster level or at namespace level. Since Capsule introduces a further segregation level, i.e. the Tenant abstraction, we can implement the PodSecurityStandard at tenant abstraction level:

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
    - kind: User
      name: alice
  namespaceOptions:
    quota: 3
  podSecurityConfiguration:
    defaults:
      enforce: "baseline"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: [oil-system]
```

Capsule controller has not to create its own `validatingwebhookconfiguration`  to enforce the policies, it just translates the above configuration in a set of labels to the namespaces within the `oil` tenant:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    capsule.clastix.io/tenant: oil
    kubernetes.io/metadata.name: oil-development
    name: oil-development
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
  name: oil-development
  ownerReferences:
  - apiVersion: capsule.clastix.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: oil
```

 and the default Pod Security Admission Controller does the magic. If the tenant owner tries to change/delete the above labels, Capsule will reconcile them to the tenant manifest.

How would the new interaction with Capsule look like? E.g.

1. What are the prerequisites for this?
2. Tenant owner creates a new _Namespace_
3. This is going to be attached to the _Tenant_
4. All the magic happens in the background

Feel free to add a diagram if that helps explain things.

# Expected behavior
A clear and concise description of what you expect to happen.

**Comment by bsctl** [comment]
This can be addressed with `spec.namespaceOptions.additionalMetadata.labels`

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  annotations:
    capsule.clastix.io/forbidden-namespace-labels: pod-security.kubernetes.io/enforce
  name: solar
spec:
  namespaceOptions:
    additionalMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
  owners:
  - kind: User
    name: alice
```

so it's just matter of documenti it.
