### ISSUE TITLE
DOC: Limit Range manifest example not correct 

### ISSUE THREAD

**Issue by YvosOnTheHub** [clastix/capsule#630]
# Bug description

There is an issue in the documentation on the following link: [https://capsule.clastix.io/docs/general/tutorial/#assign-resources-quota](https://capsule.clastix.io/docs/general/tutorial/#assign-resources-quota )

Check the **Pods and containers limits** paragraph:

```
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
...
  limitRanges:
    items:
    - type: Pod
      min:
        cpu: "50m"
        memory: "5Mi"
...
```

I believe the correct writing is ("- limits:" was missing):
```
spec:
...
  limitRanges:
    items:
      - limits: 
          - type: Pod
             min:
                cpu: "50m"
                memory: "5Mi"
...
```

thanks in advance for changing that. It will probably save time for some users
