### ISSUE TITLE
Support for RuntimeClass

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#633]
# Describe the feature

[RuntimeClass](https://kubernetes.io/docs/concepts/containers/runtime-class/) is a feature for selecting the container runtime configuration. The container runtime configuration is used to run a Pod's containers.

# What would the new user story look like?

As a Cluster Administrator, I want to limit, prevent, or allow the use of specific `RuntimeClass` to specific tenants.

# Expected behaviour

When the Tenant is enforced with a specific set of `RuntimeClass`, if the Pod is using a forbidden one, must be denied.

**Comment by oliverbaehler** [comment]
@prometherion I ll do that. I guess we are looking for same functionality as eg. PriorityClasses:

```
  runtTimeClass:
    default: "cri-o"
    allowed:
      - default
    allowedRegex: "^docker-.*$"
```

I would also add the `default` attribute and could combine it with #610. That  makes sense for you?
