### ISSUE TITLE
remove namespace from tenant

### ISSUE THREAD

**Issue by TinySong** [clastix/capsule#655]
# Bug description

how to remote namespace from tenant 

# How to reproduce

None
# Expected behavior

I want to know the way to remove a  namespace from a tenant.
# Logs

# Additional context

- Capsule version: (`capsule --version`)
  v0.1.2

**Comment by prometherion** [comment]
Hey Tony, would you like to remove the Namespace association from a Tenant while keeping its content, right?

In that case you would need to remove the `ownerReference` field and the Capsule labels at the same time.

In case it wouldn't work, we can try to debug it together.

Let me know if it works!

**Comment by TinySong** [comment]
@prometherion  thank you rely so quick. Remove `ownerReference` and `Capsule labels `work if the user is a Kubernetes cluster admin who isn't a tenant Owner. But if the user is a Tenant owner, using OIDC Token request removing ownerReference and Capsule labels doesn't work. Like this:

OIDC kubeconfig:
``` 
apiVersion: v1
kind: Config
clusters:
  - name: cluster1
    cluster:
      server: https://kube-oidc-proxy:443
      insecure-skip-tls-verify: true
contexts:
  - name: cluster1-admin
    context:
      cluster: cluster1
      user: admin
current-context: cluster1-admin
preferences:
  colors: true
users:
  - name: admin
    user:
      auth-provider:
        name: oidc
        config:
          client-id: client
          id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkNjdkMDk0NWIyZWYyOTZhNWY3NTJhZWM3MDkyNTE0MjJiMjdhM2QifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMTYubmlwLmlvL29pZGMiLCJzdWIiOiJDZ1ZoWkcxcGJoSUdhemh6WTNKayIsImF1ZCI6ImJmZi1jbGllbnQiLCJleHAiOjE2NjU1Mzk0NTcsImlhdCI6MTY2NTQ1MzA1NywiYXRfaGFzaCI6InNiQ01icW9MNlVOWmlIa3hoYVZqRXciLCJjX2hhc2giOiJmR29UUm91T2d3X0hvei1wV01obEl3IiwiZW1haWwiOiJhZG1pbkB0ZW54Y2xvdWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImdyb3VwcyI6WyJzeXN0ZW06bWFzdGVycyIsImlhbS50ZW54Y2xvdWQuY29tIiwib2JzZXJ2YWJpbGl0eSIsInJlc291cmNlLXJlYWRlciJdLCJuYW1lIjoiYWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsInBob25lIjoiIiwidXNlcmlkIjoiYWRtaW4ifQ.Gy97zhJtmCwH48FXa-5Oxff6gv2tBcnJyFogViO66yEWfFczhOYUihzHN-Sw2SJewC8VSuNYOjzPiTp1vlc81Q2sp8laHcx_p5QcH5nIFSF-uB37PvDerxjNLWA0XY0duWZtn7kPRk5beyw0-yIcV2kaeeBwleRwLbnMUQh5KBIeKsOpRkDmXmwmff9A0gkOM--CRcw281q9ocSE2L2Nq3RCs9T527Epu_ksOTyEO6Co0iYOSPnKg1sXKi1YhWPDjXRljh0SWMwx3V_PsnGrA2UpJbT1hMs-ZAs1Zm3Q_bHErRPDzxs697CwqnczmAgo-b0IoPvEWyz9mP-v88-yjQ
          idp-certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwVENDQW8yZ0F3SUJBZ0lRUG5oNW10djZScXJnMURDeW9jZmVjekFOQmdrcWhraUc5dzBCQVFzRkFEQWsKTVNJd0lBWURWUVFERXhsdmFXUmpMWE5sY25abGNpMXpaV3htYzJsbmJtVmtMV05oTUI0WERUSXlNRGt4TlRBMgpNamd6TlZvWERUSXlNVEl4TkRBMk1qZ3pOVm93SkRFaU1DQUdBMVVFQXhNWmIybGtZeTF6WlhKMlpYSXRjMlZzClpuTnBaMjVsWkMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1YOVorSmgKU1JzdDNmQ1BZSUVyWWhESjhsVkJhK240QkZBTjBFd3dYcENDZHFzVjFNWkZWcS9nZjlVbmdBV0tVSXc4L25xNQpnRzR0L3VuL1duWDAwRTJrTFIxT0I5STJoZHBVZXZTbmZ3T1Z1TVlkQmZwU3BMb01nemZ6MHRkblh5cEt2Znk1CmIwUFg5Vjk3WExPNnFFazFIUmltNUJyVHBBR0hwY0dRUmhQU3lzM3NFWi9UVEhBejA1dnJUNnhMK3RRZkJVS2cKVkF0WEVQSGpCT1plNWovb2JCSVdmMjQ5R2wrUEN1K2N6dGFzcjFUbU15NkIvYnptNmhZT2xnVEpaWFhYcEY1bAp6dmduZ0lIMFVRRGZjN3FKK0wxQVVrL0pCNXI1c0czQkt0U1NjQm5BK1E0NjJWYkRrUGYwWk9oandLSFMwNlNvCjBpOHJ0a1F5UGl1MHlQVUNBd0VBQWFPQjBqQ0J6ekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdFd1lEVlIwbEJBd3cKQ2dZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVo3OWxHMUJNVVppRwpPYWd6eFB1UWU3aWI0RFV3ZUFZRFZSMFJCSEV3YjRJYWIybGtZeTR4TnpJdU1qSXVPVFl1TVRZdWMzTnNhWEF1CmFXK0NEMnQxWW1VdGIybGtZeTF3Y205NGVZSVhhM1ZpWlMxdmFXUmpMWEJ5YjNoNUxtUmxabUYxYkhTQ0cydDEKWW1VdGIybGtZeTF3Y205NGVTNWtaV1poZFd4MExuTjJZNGNFckJaZ0VJY0VyQlpnaFRBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFaazd6MHFXQ2NrL1ltNkVnbExZSGhwUHpnNm9aVk1uV1AzMGIwOERZSnlSWlpFR0hOTmduCmFDMnBqVVdkZkhqeGhmekRMRDExSzlDM1pVeExiQnZGcWQwdjdhbWxlRk1PWlJQK1JzUm10YWZIWXFUanhFRTYKcEd4WHdRS0M2aFZzd0h5WHpCZWVhRGhMMnU4SUQ2akF0ZkRxbERldytWWjZLNEJ1SVhPdXNOUHh2aC9GQW1tcgpBMXlMSmFDVVZsTzBLb1A1UVdOSTRvMFJOVmtsRS9WSUJHZTZkdElSdnRvYjU0MEZGR0lrTEpHMHdVUWRuaHhiCkw0UXB3NXlOV0lNM052ZmM0d09zeWlMbDgvTUt2WmdEdU5JSXdlRjl0UVF0M01JdThlNnYrbFBQc0FzUU5XVEgKOUh2cUdKY05xNnhNK1JhZUM2ZGhRN1htbGtBSTRpWHljUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          idp-issuer-url: https://oidc-server:443
          refresh-token: ChlrcHUycjJlcXE0anl6YXd0ZG1heHZueG51Ehlsb2JzcndvZmthNDc3NGtvZ3h3cXJzdXlk
```
kubectl commmand:
```
 kubectl --kubeconfig=./admin-kubeconfig.yaml  patch namespace testing --v=8 -p '{"metadata": {"ownerReferences": null,"labels":{"capsule.clastix.io/tenant":null}}}' --type="merge"
```
this way doesn't work.
