### ISSUE TITLE
feat: default pod security standards

### ISSUE THREAD

**Issue by oliverbaehler** [clastix/capsule#680]
# Describe the feature

Currently we don't allow users to specify any pod security relevant properties (`securityContext` on pod and container level). By default we should deliver the capsule installation with all the necessary configuration, to run within a common pod security profile environment. Preferably, all components should be executable in a [restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) profile.

# What would the new user story look like?

Add pod security and ingress options to make the default installation of capsule as secure as possible by default.

**Comment by oliverbaehler** [comment]
Running the manager with the following securityContext (Container):

```
securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1002
          runAsNonRoot: true
          runAsUser: 1002
```

Does not allow to run Capsule. It seems the `tls-controller` needs more privileges. The logs look like this:

```
{"level":"info","ts":"2023-01-09T11:11:46.239Z","logger":"setup","msg":"Capsule Version v0.1.3 b61db25.dev.dirty"}
{"level":"info","ts":"2023-01-09T11:11:46.239Z","logger":"setup","msg":"Build from: git@github.com:clastix/capsule.git"}
{"level":"info","ts":"2023-01-09T11:11:46.239Z","logger":"setup","msg":"Build date: 2023-01-05T23:52:03"}
{"level":"info","ts":"2023-01-09T11:11:46.239Z","logger":"setup","msg":"Go Version: go1.18.9"}
{"level":"info","ts":"2023-01-09T11:11:46.239Z","logger":"setup","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":"2023-01-09T11:11:46.347Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2023-01-09T11:11:46.444Z","logger":"controllers.TLS","msg":"Generating new TLS certificate"}
{"level":"error","ts":"2023-01-09T11:12:24.342Z","logger":"controllers.TLS","msg":"cannot update Capsule TLS","error":"client rate limiter Wait returned an error: context canceled","stacktrace":"main.main\n\t/workspace/main.go:192\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"error","ts":"2023-01-09T11:12:24.343Z","logger":"setup","msg":"unable to reconcile Capsule TLS secret","error":"client rate limiter Wait returned an error: context canceled","stacktrace":"main.main\n\t/workspace/main.go:193\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

Pod runs into Crashloopbackoff. I will take a very wild guess, that it has something to do with the random algorithem to generate the certificate. because if the TLS certificate is created correctly, it's not failing (since no update has to be done). My initial assumption was, that we have to deal with a privileged operation on the random device, so requiring following capability:

```
CAP_SYS_ADMIN
             ....
              * perform privileged [ioctl(2)](https://man7.org/linux/man-pages/man2/ioctl.2.html) operations on the
                /dev/random device (see [random(4)](https://man7.org/linux/man-pages/man4/random.4.html));
             ...
```

But testing with that capability, didnt really change anything:

```
securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1002
          runAsNonRoot: true
          runAsUser: 1002
```

I will have to dig deeper.

**Comment by oliverbaehler** [comment]
Runs with:

```
          capabilities:
            add:
            - NET_BROADCAST
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SYS_PTRACE
            - SYS_BOOT
            - LEASE
            - SETFCAP
            drop:
            - ALL
```
