### ISSUE TITLE
feat: Allow templating in GlobalTenantResource and TenantResource

### ISSUE THREAD

**Issue by h4wkmoon** [clastix/capsule#688]
# Describe the feature

It would be nice to allow some templating in GlobalTenantResource and TenantResource. For now, I can see 2 variables that could be templated: the tenant name, and the namespace name.

We have a use-case where we want to deploy an ingress in specific namespaces for specific tenants. The hostname of the ingress has the tenant name in it.

# What would the new user story look like?

As a cluster-admin, I would like to be able to use tenant name, and namespace name in the manifest of resource generated by  globaltenantresources. 
As a tenant owner, I would like to be able to use tenant name, and namespace name in the manifest of resource generated by  tenantresources. 

# Expected behavior

This resource would create an ingress with the interpolated hostname.
Double curly brackets is just a proposal. Any other templating synthax may be ok. Kyverno has similar features. It can be used as an example.

```
apiVersion: capsule.clastix.io/v1beta2
kind: GlobalTenantResource
metadata:
  name: some-ingress
spec:
  tenantSelector:
    matchLabels:
      somelabel: "somevalue"
  resyncPeriod: 60s
  resources:
    - namespaceSelector:
        matchLabels:
          somelabel: "somevalue"
      rawItems:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: something
        spec:
          rules:
          - host: something.{{tenant_name}}.mydomain
            [...]
```
