### ISSUE TITLE
Tenant status conversion between v1beta1 and v1beta2 is broken

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule#691]
```
$: cat <<EOF | kubectl; apply -f -
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: test
spec:
  owners:
  - kind: User
    name: alice
EOF

The Tenant "test" is invalid: status.state: Unsupported value: "": supported values: "Cordoned", "Active"
```
