### ISSUE TITLE
Force specific labels for specific namespaces

### ISSUE THREAD

**Issue by h4wkmoon** [clastix/capsule#698]
# Describe the feature

It would be a addition to the feature forbiddenLabels. For those forbiddenlabels, lets allow the cluster admin to set them, with a specific value, namespace by namespace.

# What would the new user story look like?
```
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
spec:
  namespaceOptions:
     forcedMetadata:
    - namespaces: 
       - namespace1
       - namespace10
      labels:
          label1: value1
          label2: value2
    - namespaces: 
      - namespace2
      - namespace21
      labels:
          label1: another-value1
          label2: another-value2          
```
With this manifest, namespaces 1 and 10 would have some labels enforced on them. And ns 2 and 21, another set of labels.

# Use case
Labels can be used in netpol, as mentionned in [this doc](https://capsule.clastix.io/docs/general/tutorial/#deny-labels-and-annotations-on-namespaces). This feature would allow to a cluster admin to manage these labels at a tenant level.
