### ISSUE TITLE
CRD URL's in Upgrade Guide Are Invalid

### ISSUE THREAD

**Issue by jwilkicki** [clastix/capsule#730]
# Bug description

I am attempting to follow the upgrade guide to migrate from v0.1.3 to v0.3.0 and am having problems with the upgrade steps.  Specifically, the two CRD's called out to be upgraded:

https://raw.githubusercontent.com/clastix/capsule/v0.2.1/config/crd/bases/capsuleconfiguration-crd.yaml

and

https://raw.githubusercontent.com/clastix/capsule/v0.3.0/config/crd/bases/tenant-crd.yaml

result in 404 errors when I tried to install them with kubectl and when I tried to access them through my web browser to confirm.

I looked around the source code for the chart to try and find something with the same file name.  I then scaled down the deployment, deleted the default capsule configuration and applied these CRD's:  

```
kubectl apply -f https://raw.githubusercontent.com/clastix/capsule/v0.3.0/charts/capsule/crds/capsuleconfiguration-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/clastix/capsule/v0.3.0/charts/capsule/crds/tenant-crd.yaml
```
After applying these CRD's and re-running the helm install, I get the following error from helm (via Terraform):

```shell
error validating data: ValidationError(CapsuleConfiguration.spec): missing required field "nodeMetadata" in io.clastix.capsule.v1beta2.CapsuleConfiguration.spec
```
and the capsule deployment is still set at zero replicas.

# How to reproduce

1. Install capsule 0.2.0 chart with app version 0.1.3
2. Scale down capsule-controller-manager version 0.1.3 with kubectl scale
3. Apply CRD's as specified in documentation (will fail with 404)
4. Apply CRD's provided in this issue as intended replacements
5. Upgrade the Helm chart to capsule 0.4.0

# Expected behavior

I expected Capsule to upgrade to version 0.3.0.

# Logs

N/A

# Additional context

- Capsule version: 0.1.3  (upgrading to 0.3.0)
- Helm Chart version: capsule-0.2.0 (upgrading to 0.4.0)
- Kubernetes version: Client Version: v1.26.1 Kustomize Version: v4.5.7  Server Version: v1.22.17-eks-48e63af

The following values were used for the Helm release:

```yaml
affinity: {}
certManager:
  generateCertificates: false
customAnnotations: {}
customLabels: {}
jobs:
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/clastix/kubectl
    tag: ""
manager:
  hostNetwork: false
  image:
    pullPolicy: IfNotPresent
    repository: clastix/capsule
    tag: ""
  imagePullSecrets: []
  kind: Deployment
  livenessProbe:
    httpGet:
      path: /healthz
      port: 10080
  options:
    capsuleUserGroups:
    - capsule.clastix.io
    - system:serviceaccounts:argocd
    forceTenantPrefix: false
    generateCertificates: true
    logLevel: "4"
    protectedNamespaceRegex: ""
  readinessProbe:
    httpGet:
      path: /readyz
      port: 10080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
mutatingWebhooksTimeoutSeconds: 30
nodeSelector: {}
podAnnotations: {}
podSecurityPolicy:
  enabled: false
priorityClassName: ""
replicaCount: 1
serviceAccount:
  annotations: {}
  create: true
  name: capsule
serviceMonitor:
  annotations: {}
  enabled: false
  endpoint:
    interval: 15s
    metricRelabelings: []
    relabelings: []
    scrapeTimeout: ""
  labels: {}
  matchLabels: {}
  namespace: ""
  serviceAccount:
    name: capsule
    namespace: capsule-system
  targetLabels: []
tls:
  create: true
  enableController: true
  name: ""
tolerations: []
validatingWebhooksTimeoutSeconds: 30
webhooks:
  cordoning:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  ingresses:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  namespaceOwnerReference:
    failurePolicy: Fail
  namespaces:
    failurePolicy: Fail
  networkpolicies:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  nodes:
    failurePolicy: Fail
  persistentvolumeclaims:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  pods:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  services:
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
  tenants:
    failurePolicy: Fail
```
