### ISSUE TITLE
name label added to namespace in not prefixed with capsule.clastix.io

### ISSUE THREAD

**Issue by sagar-jadhav** [clastix/capsule#754]
# Bug description

Namespace has the label `name` added by Capsule controller which is not prefixed by `capsule.clastix.io`

# How to reproduce

Create a Tenant `oil` as a cluster admin

```
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
```
Create a namespace `oil-db` as a Alice user

```
kubectl create ns oil-db
```

Describe the namespace `oil-db` as a Alice user

```
kubectl describe ns oil-db

Name:         oil-db
Labels:       capsule.clastix.io/tenant=oil
              name=oil-db

No resource quota.
```
# Expected behavior

`name` label should be prefixed with `capsule.clastix.io` in the `oil-db` namespace as it is added by Capsule controller

# Additional context

- Helm Chart version: v0.3.1
