### ISSUE TITLE
Should not require cluster-admin ClusterRoleBinding

### ISSUE THREAD

**Issue by erikgb** [clastix/capsule#771]
# Bug description

It appears, from installation manifests and Helm charts, that Capsule currently requires access to the highly elevated cluster-admin cluster role. This is something I think is usually untrue and should be avoided - following the least-privilege principles. 

From a comment from @prometherion on Slack (https://kubernetes.slack.com/archives/C03GETTJQRL/p1686314158366209?thread_ts=1686311373.987009&cid=C03GETTJQRL), it seems like this is due to "provide admin capabilities to Tenant Owners".

If that is the only rationale, we have been faced with the same issue, and have found a solution to grant stricter RBAC than cluster-admin. Note the last rule granting the `bind` verb to the admin cluster role.

````yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-admin-provider
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - bind
    resourceNames:
      - admin
````
