### ISSUE TITLE
Support for clusters with OwnerReferencesPermissionEnforcement admission plugin enabled

### ISSUE THREAD

**Issue by erikgb** [clastix/capsule#773]
# Bug description

We are performing a Capsule POC on OpenShift, and it turns out that Capsule misses RBAC configuration to support clusters with [OwnerReferencesPermissionEnforcement admission plugin](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) enabled. OpenShift enables this by default.

# How to reproduce

Pre-requisite: A Kubernetes cluster with OwnerReferencesPermissionEnforcement admission plugin enabled.

1. Establish a new tenant
2. As a tenant owner, attempt to create a new namespace
3. The create namespace request is rejected with the following error message: `namespaces "erikbo-egb-test" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on`

# Expected behavior

The tenant owner is allowed to create a new namespace without any errors.

I am pretty sure that the error is caused by the Capsule namespace admission webhook. It adds an owner reference to the namespace, pointing to the tenant resource with `blockOwnerDeletion: true`. Which a `capsule-namespace-provisioner` is not allowed to do. I was able to work around the issue by adding a new cluster role with the missing permissions and bind this new cluster role to the `capsuleUserGroups`.

````yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capsule-namespace-provisioner-fix
rules:
  - verbs:
      - update
    apiGroups:
      - capsule.clastix.io
    resources:
      - tenants/finalizers
````

# Logs

If applicable, please provide logs of `capsule`.

I don't think the logs are relevant in this case.

# Additional context

- Capsule version: latest + @prometherion Flux impersonate hot-fix
- Helm Chart version: N/A
- Kubernetes version: Openshift 4.12.13 (K8s v1.25.8+27e744f)
