### ISSUE TITLE
Support for additional labels and annotations to be inherited by tenant namespaces

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#78]
# Describe the feature
The idea is to leave an additional section in the Tenant manifest where the Cluster admin can specify additional labels and/or annotations to apply to the namespaces belonging to the tenant. Initially, there are no specific semantics assigned to these labels, they just will be assigned to the namespaces in the tenant. This can be useful to the adopters of Capsule to implement their specific use cases.

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  additionalNamespaceLabels:
    capsule.clastix.io/backup: "true"
    capsule.clastix.io/billable: "true"
    capsule.clastix.io/do_stuff: "once"
...
```
# What would the new user story look like?

1. The cluster admin creates a tenant with this additional fields
2. Tenant owner creates a new _Namespace_
3. All the namespaces created in this tenant will inherit the labels
4. Depending on the case, additional business logics can be implemented by using the labels. 

Please note the specific business logic is not part of the Capsule. Instead it is left to the cluster admin and or to the tenant owner.

# Expected behavior
All the namespaces created in the tenant inherit the labels.
