### ISSUE TITLE
ValidationWebhookConfiguration blocked kube-ovn-cni pods

### ISSUE THREAD

**Issue by aminmr** [clastix/capsule#787]
# Bug description

I deployed a k8s cluster with version 1.25.6.
I deployed Kube-OVN as my cluster CNI. 
And I also deployed capsule v0.3.1
My cluster went to disaster (masters were down, and cluster pods were not in a running state due to worker failure), and the capsule pods were not available anymore.
The kube-OVN had a DaemonSet called `kube-ovn-cni`, which is responsible for applying IPs for pods and etc.
`kube-ovn-cni` pods have been blocked via `nodes.capsule.clastix.io` webhook in the capsule `ValidationWebhookConfiguration`, and the pods went to the `CrashLoopBackoff` state. The error is:
```
"failed to initialize ovn chassis annotation" err="Internal error occurred: failed calling webhook \"nodes.capsule.clastix.io\": failed to call webhook: Post \"https://capsule-webhook-service.caas.svc:443/nodes?timeout=30s\": no endpoints available for service \"capsule-webhook-service\""
```
This broke the cluster functionality, and even the capsule pods couldn't get any IPs from CNI. So a loop has occurred.
I deleted capsule ValidationWebhookConfiguration temporarily and the CNI went functional. Then apply the ValidationWebhookConfiguration again for capsule functionality.
How should I fix this problem without deleting the capsule `ValidationWebhookConfiguration`?
# How to reproduce

1. Deploy k8s cluster with Kube-OVN CNI
2. Deploy the capsule with the helm or your preferred way.
3. After checking that everything is alright, delete the `kube-ovn-cni` pod in `kube-system` namespace(This is a DaemonSet, and you can delete any pod on any node)
4. The pod will be going to `CrashLoopBackOff` state
5. Read the pod logs 

# Expected behavior

The Capsule Admission webhook doesn't create any problems for Kube-OVN.
# Logs
kube-ovn-cni pod:
```
"failed to initialize ovn chassis annotation" err="Internal error occurred: failed calling webhook \"nodes.capsule.clastix.io\": failed to call webhook: Post \"https://capsule-webhook-service.caas.svc:443/nodes?timeout=30s\": no endpoints available for service \"capsule-webhook-service\""
```

# Additional context

- Capsule version: capsule:v0.3.1
- Helm Chart version: 0.4.1
- Kubernetes version: 1.25.6

The webhook section which is match:
```yaml
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: xxx
    service:
      name: capsule-webhook-service
      namespace: caas
      path: /nodes
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: nodes.capsule.clastix.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - nodes
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```
