### ISSUE TITLE
Support for additional labels and annotations to be inherited by tenant services

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule#79]
# Describe the feature
The idea is to leave an additional section in the Tenant manifest where the Cluster admin can specify additional labels and/or annotations to apply to the services created in the tenant. Initially, there are no specific semantics assigned to these labels, they just will be assigned to the services and endpoints in the tenant. This can be useful to the adopters of Capsule to implement their specific use cases.

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  additionalServiceLabels:
    capsule.clastix.io/do_stuff: "always"
```
...

# What would the new user story look like?

1. The cluster admin creates a tenant with this additional fields
2. Tenant owner creates a new _Namespace_
3. Tenant owner creates new services in the tenant namespace
3. All the services and related endpoints created in this tenant will inherit the labels
4. Depending on the case, additional business logics can be implemented by using the labels. 

Please note the specific business logic is not part of the Capsule. Instead it is left to the cluster admin and or to the tenant owner.

# Expected behavior
All the services and related endpoints created in the tenant inherit the labels.
