### ISSUE TITLE
Manually adding namespaces to tenant

### ISSUE THREAD

**Issue by micke-post** [clastix/capsule#813]
Hi,
we are running an aks cluster with several tenants. What we are currently trying to do is deploy additional resources into all tenants. We do that by creating a new namespace that's prefixed with the tenant name since forceTeantPrefix is enabled on the cluster, and then deploying whatever resources are needed with helm.

The account used to create the new namespace is not part of the capsule user groups as it also needs to be able to create and manage system namespaces that are not part of any tenant. But as a result that also means that the namespaces that are created by that user are not automatically assigned to any tenant.

I'm wondering what best practice for this use case is. Should we manually set the capsule.clastix.io/tenant tag and tenant owner reference when creating the namespace? Or is there a way tell capsule to adopt a namespace and set the needed metadata automatically?

**Comment by prometherion** [comment]
Thanks for the question!

Namespace Tenant ownership does not rely on their labels since these could be easily modified by Tenant Owners, and escaping the Tenant boundaries by just knowing in advance the name of other Tenants.

Currently, the Namespace ownership is backed by the `OwnerReferece` metadata which references the UID of the Tenant resource. Still, it's not 100% secure, at least Capsule, starting from the latest versions (v0.3.3, such as 75525ac19254b0c5111e34d7985e2be7bc8b1ac1) is blocking the change of that field.

So far, I was successfully able to add Namespaces to a Tenant even tho I wasn't the owner by adding the correct `OwnerReference` properties: I know it's not very handy if you're using CI/CD tools, at the same time, the project is sticking to the concept of self-service by tenant owners.

We're open in earing feedback from the community members, tho, let me know your thoughts about this approach.

**Comment by micke-post** [comment]
I actually think that approach is fine. Getting the UID of a tenant and then "manually" creating a namespace isn't really a lot of overhead, especially when automating it anyway. I just wasn't sure if that's the way to go or if there is a different, proper, way that I overlooked in the documentation.

**Comment by prometherion** [comment]
Also, I forgot to share that somebody are taking advantage of Kubernetes jobs, along with the release, by running `kubectl create ns` with the user impersonation (e.g. `--as` and `--as-group`).

**Comment by micke-post** [comment]
> Currently, the Namespace ownership is backed by the `OwnerReferece` metadata which references the UID of the Tenant resource. Still, it's not 100% secure, at least Capsule, starting from the latest versions (v0.3.3, such as [75525ac](https://github.com/clastix/capsule/commit/75525ac19254b0c5111e34d7985e2be7bc8b1ac1)) is blocking the change of that field.

Yeah, I actually ran into that 😄
One of the requirements that we had was the deployment of the service should be self-contained in a helm chart, and needed to be idempotent. Which turned out to be bit of a challenge since there's no real way to tell helm to create a customized namespace if it doesn't exist, but at the same time not create a namespace if it already exists and instead adopt it into a tenant. At least not with the restriction of having to use .Release.Namespace since nginx is relying on it.

We ultimately ended up using a helm job to the helm chart that runs a kubectl script at the end of the deployment. I'll leave the relevant portion here in case someone runs into the same problem.

```
{{- if .Values.tenant.uid }}
apiVersion: batch/v1
kind: Job
metadata:
  name: job-set-nginx-namespace-owner
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: nginx-namespace-owner-assigner
      containers:
      - name: nginx-namespace-owner
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command: 
        - sh
        - -c 
        - >
          echo "Patching namespace {{ .Release.Namespace }} with ownerReference" ; 
          if kubectl get namespace {{ .Release.Namespace }} -o jsonpath='{.metadata.ownerReferences[0].kind}' | grep -q "Tenant"; then
            echo "OwnerReference already exists and is of kind Tenant. Capsule prevents the modification of the OwnerReference field. Exiting job..."
          else
            kubectl patch namespace {{ .Release.Namespace }} --patch '{"metadata":{"ownerReferences":[{"apiVersion":"capsule.clastix.io/v1beta2","blockOwnerDeletion":true,"controller":true,"kind":"Tenant","name":"{{ .Values.tenant.name }}","uid":"{{ .Values.tenant.uid }}"}]}}'
          fi

  backoffLimit: 1
{{- end }}
```
The job also needs a service account, a role with get and patch permissions on the namespace and a role assignment to glue everything together, but that's mostly just default boilerplate.
