### ISSUE TITLE
Support for regular expressions in ingressClasses and storageClasses

### ISSUE THREAD

**Issue by MaxFedotov** [clastix/capsule#87]
# Describe the feature

Right now for ingress\storage classes you need to pass an array of distinct values. In our env, when user orders a tenant in k8s cluster, he can specify if he wants dedicated ingress nodes and which ingress he wants (e.g. haproxy\nginx) and then we provision separate nodes with specified ingresses. We want to name these ingress classes using following naming convention: {tenantName}-haproxy, {tenantName-nginx}. So for us, it would be much easier to be able to pass regexp in ingressClasses\storageClasses.

# What would the new user story look like?

Tenant admin will be able to create tenants with following options (as per discussion with @prometherion):
```
ingressClasses:
  allowed:
  - class-with-no-regex
  - another-class
  allowedRegex: ^oil-.*$
storageClasses:
  allowed:
  - class-with-no-regex
  - another-class
  allowedRegex: ^oil-.*$
```
